/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 

API version: 1.2.0
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the AddCredits200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddCredits200Response{}

// AddCredits200Response struct for AddCredits200Response
type AddCredits200Response struct {
	Success *bool `json:"success,omitempty"`
	Balance *CreditBalanceInfo `json:"balance,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewAddCredits200Response instantiates a new AddCredits200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddCredits200Response() *AddCredits200Response {
	this := AddCredits200Response{}
	return &this
}

// NewAddCredits200ResponseWithDefaults instantiates a new AddCredits200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddCredits200ResponseWithDefaults() *AddCredits200Response {
	this := AddCredits200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *AddCredits200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddCredits200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *AddCredits200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *AddCredits200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *AddCredits200Response) GetBalance() CreditBalanceInfo {
	if o == nil || IsNil(o.Balance) {
		var ret CreditBalanceInfo
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddCredits200Response) GetBalanceOk() (*CreditBalanceInfo, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *AddCredits200Response) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given CreditBalanceInfo and assigns it to the Balance field.
func (o *AddCredits200Response) SetBalance(v CreditBalanceInfo) {
	o.Balance = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AddCredits200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddCredits200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AddCredits200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AddCredits200Response) SetMessage(v string) {
	o.Message = &v
}

func (o AddCredits200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddCredits200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableAddCredits200Response struct {
	value *AddCredits200Response
	isSet bool
}

func (v NullableAddCredits200Response) Get() *AddCredits200Response {
	return v.value
}

func (v *NullableAddCredits200Response) Set(val *AddCredits200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAddCredits200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAddCredits200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddCredits200Response(val *AddCredits200Response) *NullableAddCredits200Response {
	return &NullableAddCredits200Response{value: val, isSet: true}
}

func (v NullableAddCredits200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddCredits200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


