/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 

API version: 1.2.0
Contact: support@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LinkOpportunity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkOpportunity{}

// LinkOpportunity struct for LinkOpportunity
type LinkOpportunity struct {
	// AI-calculated relevance score (0-1)
	RelevanceScore float32 `json:"relevanceScore"`
	// Suggested anchor text
	AnchorText string `json:"anchorText"`
	// Context where the link should be placed
	Context *string `json:"context,omitempty"`
	SourcePage PageInfo `json:"sourcePage"`
	TargetPage PageInfo `json:"targetPage"`
	// AI reasoning for the suggestion
	Reasoning *string `json:"reasoning,omitempty"`
}

type _LinkOpportunity LinkOpportunity

// NewLinkOpportunity instantiates a new LinkOpportunity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkOpportunity(relevanceScore float32, anchorText string, sourcePage PageInfo, targetPage PageInfo) *LinkOpportunity {
	this := LinkOpportunity{}
	this.RelevanceScore = relevanceScore
	this.AnchorText = anchorText
	this.SourcePage = sourcePage
	this.TargetPage = targetPage
	return &this
}

// NewLinkOpportunityWithDefaults instantiates a new LinkOpportunity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkOpportunityWithDefaults() *LinkOpportunity {
	this := LinkOpportunity{}
	return &this
}

// GetRelevanceScore returns the RelevanceScore field value
func (o *LinkOpportunity) GetRelevanceScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RelevanceScore
}

// GetRelevanceScoreOk returns a tuple with the RelevanceScore field value
// and a boolean to check if the value has been set.
func (o *LinkOpportunity) GetRelevanceScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RelevanceScore, true
}

// SetRelevanceScore sets field value
func (o *LinkOpportunity) SetRelevanceScore(v float32) {
	o.RelevanceScore = v
}

// GetAnchorText returns the AnchorText field value
func (o *LinkOpportunity) GetAnchorText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AnchorText
}

// GetAnchorTextOk returns a tuple with the AnchorText field value
// and a boolean to check if the value has been set.
func (o *LinkOpportunity) GetAnchorTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AnchorText, true
}

// SetAnchorText sets field value
func (o *LinkOpportunity) SetAnchorText(v string) {
	o.AnchorText = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *LinkOpportunity) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkOpportunity) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *LinkOpportunity) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *LinkOpportunity) SetContext(v string) {
	o.Context = &v
}

// GetSourcePage returns the SourcePage field value
func (o *LinkOpportunity) GetSourcePage() PageInfo {
	if o == nil {
		var ret PageInfo
		return ret
	}

	return o.SourcePage
}

// GetSourcePageOk returns a tuple with the SourcePage field value
// and a boolean to check if the value has been set.
func (o *LinkOpportunity) GetSourcePageOk() (*PageInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourcePage, true
}

// SetSourcePage sets field value
func (o *LinkOpportunity) SetSourcePage(v PageInfo) {
	o.SourcePage = v
}

// GetTargetPage returns the TargetPage field value
func (o *LinkOpportunity) GetTargetPage() PageInfo {
	if o == nil {
		var ret PageInfo
		return ret
	}

	return o.TargetPage
}

// GetTargetPageOk returns a tuple with the TargetPage field value
// and a boolean to check if the value has been set.
func (o *LinkOpportunity) GetTargetPageOk() (*PageInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPage, true
}

// SetTargetPage sets field value
func (o *LinkOpportunity) SetTargetPage(v PageInfo) {
	o.TargetPage = v
}

// GetReasoning returns the Reasoning field value if set, zero value otherwise.
func (o *LinkOpportunity) GetReasoning() string {
	if o == nil || IsNil(o.Reasoning) {
		var ret string
		return ret
	}
	return *o.Reasoning
}

// GetReasoningOk returns a tuple with the Reasoning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkOpportunity) GetReasoningOk() (*string, bool) {
	if o == nil || IsNil(o.Reasoning) {
		return nil, false
	}
	return o.Reasoning, true
}

// HasReasoning returns a boolean if a field has been set.
func (o *LinkOpportunity) HasReasoning() bool {
	if o != nil && !IsNil(o.Reasoning) {
		return true
	}

	return false
}

// SetReasoning gets a reference to the given string and assigns it to the Reasoning field.
func (o *LinkOpportunity) SetReasoning(v string) {
	o.Reasoning = &v
}

func (o LinkOpportunity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkOpportunity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["relevanceScore"] = o.RelevanceScore
	toSerialize["anchorText"] = o.AnchorText
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	toSerialize["sourcePage"] = o.SourcePage
	toSerialize["targetPage"] = o.TargetPage
	if !IsNil(o.Reasoning) {
		toSerialize["reasoning"] = o.Reasoning
	}
	return toSerialize, nil
}

func (o *LinkOpportunity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"relevanceScore",
		"anchorText",
		"sourcePage",
		"targetPage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkOpportunity := _LinkOpportunity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinkOpportunity)

	if err != nil {
		return err
	}

	*o = LinkOpportunity(varLinkOpportunity)

	return err
}

type NullableLinkOpportunity struct {
	value *LinkOpportunity
	isSet bool
}

func (v NullableLinkOpportunity) Get() *LinkOpportunity {
	return v.value
}

func (v *NullableLinkOpportunity) Set(val *LinkOpportunity) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkOpportunity) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkOpportunity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkOpportunity(val *LinkOpportunity) *NullableLinkOpportunity {
	return &NullableLinkOpportunity{value: val, isSet: true}
}

func (v NullableLinkOpportunity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkOpportunity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


