/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the RollbackImplementationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RollbackImplementationRequest{}

// RollbackImplementationRequest struct for RollbackImplementationRequest
type RollbackImplementationRequest struct {
	// Optional reason for rollback
	Reason *string `json:"reason,omitempty"`
}

// NewRollbackImplementationRequest instantiates a new RollbackImplementationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRollbackImplementationRequest() *RollbackImplementationRequest {
	this := RollbackImplementationRequest{}
	return &this
}

// NewRollbackImplementationRequestWithDefaults instantiates a new RollbackImplementationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRollbackImplementationRequestWithDefaults() *RollbackImplementationRequest {
	this := RollbackImplementationRequest{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *RollbackImplementationRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackImplementationRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *RollbackImplementationRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *RollbackImplementationRequest) SetReason(v string) {
	o.Reason = &v
}

func (o RollbackImplementationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RollbackImplementationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableRollbackImplementationRequest struct {
	value *RollbackImplementationRequest
	isSet bool
}

func (v NullableRollbackImplementationRequest) Get() *RollbackImplementationRequest {
	return v.value
}

func (v *NullableRollbackImplementationRequest) Set(val *RollbackImplementationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRollbackImplementationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRollbackImplementationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollbackImplementationRequest(val *RollbackImplementationRequest) *NullableRollbackImplementationRequest {
	return &NullableRollbackImplementationRequest{value: val, isSet: true}
}

func (v NullableRollbackImplementationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollbackImplementationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


