/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 

API version: 1.2.0
Contact: support@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the VerifyContent200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyContent200Response{}

// VerifyContent200Response struct for VerifyContent200Response
type VerifyContent200Response struct {
	Success *bool `json:"success,omitempty"`
	Verification *ContentVerification `json:"verification,omitempty"`
}

// NewVerifyContent200Response instantiates a new VerifyContent200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyContent200Response() *VerifyContent200Response {
	this := VerifyContent200Response{}
	return &this
}

// NewVerifyContent200ResponseWithDefaults instantiates a new VerifyContent200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyContent200ResponseWithDefaults() *VerifyContent200Response {
	this := VerifyContent200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *VerifyContent200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyContent200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *VerifyContent200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *VerifyContent200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetVerification returns the Verification field value if set, zero value otherwise.
func (o *VerifyContent200Response) GetVerification() ContentVerification {
	if o == nil || IsNil(o.Verification) {
		var ret ContentVerification
		return ret
	}
	return *o.Verification
}

// GetVerificationOk returns a tuple with the Verification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyContent200Response) GetVerificationOk() (*ContentVerification, bool) {
	if o == nil || IsNil(o.Verification) {
		return nil, false
	}
	return o.Verification, true
}

// HasVerification returns a boolean if a field has been set.
func (o *VerifyContent200Response) HasVerification() bool {
	if o != nil && !IsNil(o.Verification) {
		return true
	}

	return false
}

// SetVerification gets a reference to the given ContentVerification and assigns it to the Verification field.
func (o *VerifyContent200Response) SetVerification(v ContentVerification) {
	o.Verification = &v
}

func (o VerifyContent200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyContent200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Verification) {
		toSerialize["verification"] = o.Verification
	}
	return toSerialize, nil
}

type NullableVerifyContent200Response struct {
	value *VerifyContent200Response
	isSet bool
}

func (v NullableVerifyContent200Response) Get() *VerifyContent200Response {
	return v.value
}

func (v *NullableVerifyContent200Response) Set(val *VerifyContent200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyContent200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyContent200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyContent200Response(val *VerifyContent200Response) *NullableVerifyContent200Response {
	return &NullableVerifyContent200Response{value: val, isSet: true}
}

func (v NullableVerifyContent200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyContent200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


