/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the PagePricingPagePacksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagePricingPagePacksInner{}

// PagePricingPagePacksInner struct for PagePricingPagePacksInner
type PagePricingPagePacksInner struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Pages *int32 `json:"pages,omitempty"`
	Price *float32 `json:"price,omitempty"`
}

// NewPagePricingPagePacksInner instantiates a new PagePricingPagePacksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagePricingPagePacksInner() *PagePricingPagePacksInner {
	this := PagePricingPagePacksInner{}
	return &this
}

// NewPagePricingPagePacksInnerWithDefaults instantiates a new PagePricingPagePacksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagePricingPagePacksInnerWithDefaults() *PagePricingPagePacksInner {
	this := PagePricingPagePacksInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PagePricingPagePacksInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagePricingPagePacksInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PagePricingPagePacksInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PagePricingPagePacksInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PagePricingPagePacksInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagePricingPagePacksInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PagePricingPagePacksInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PagePricingPagePacksInner) SetName(v string) {
	o.Name = &v
}

// GetPages returns the Pages field value if set, zero value otherwise.
func (o *PagePricingPagePacksInner) GetPages() int32 {
	if o == nil || IsNil(o.Pages) {
		var ret int32
		return ret
	}
	return *o.Pages
}

// GetPagesOk returns a tuple with the Pages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagePricingPagePacksInner) GetPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.Pages) {
		return nil, false
	}
	return o.Pages, true
}

// HasPages returns a boolean if a field has been set.
func (o *PagePricingPagePacksInner) HasPages() bool {
	if o != nil && !IsNil(o.Pages) {
		return true
	}

	return false
}

// SetPages gets a reference to the given int32 and assigns it to the Pages field.
func (o *PagePricingPagePacksInner) SetPages(v int32) {
	o.Pages = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *PagePricingPagePacksInner) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagePricingPagePacksInner) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *PagePricingPagePacksInner) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *PagePricingPagePacksInner) SetPrice(v float32) {
	o.Price = &v
}

func (o PagePricingPagePacksInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagePricingPagePacksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Pages) {
		toSerialize["pages"] = o.Pages
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullablePagePricingPagePacksInner struct {
	value *PagePricingPagePacksInner
	isSet bool
}

func (v NullablePagePricingPagePacksInner) Get() *PagePricingPagePacksInner {
	return v.value
}

func (v *NullablePagePricingPagePacksInner) Set(val *PagePricingPagePacksInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePagePricingPagePacksInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePagePricingPagePacksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagePricingPagePacksInner(val *PagePricingPagePacksInner) *NullablePagePricingPagePacksInner {
	return &NullablePagePricingPagePacksInner{value: val, isSet: true}
}

func (v NullablePagePricingPagePacksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagePricingPagePacksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


