/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the PageAllowance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageAllowance{}

// PageAllowance struct for PageAllowance
type PageAllowance struct {
	Allowance *PageAllowanceInfo `json:"allowance,omitempty"`
	UsageHistory []PageAllowanceUsageHistoryInner `json:"usageHistory,omitempty"`
}

// NewPageAllowance instantiates a new PageAllowance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageAllowance() *PageAllowance {
	this := PageAllowance{}
	return &this
}

// NewPageAllowanceWithDefaults instantiates a new PageAllowance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageAllowanceWithDefaults() *PageAllowance {
	this := PageAllowance{}
	return &this
}

// GetAllowance returns the Allowance field value if set, zero value otherwise.
func (o *PageAllowance) GetAllowance() PageAllowanceInfo {
	if o == nil || IsNil(o.Allowance) {
		var ret PageAllowanceInfo
		return ret
	}
	return *o.Allowance
}

// GetAllowanceOk returns a tuple with the Allowance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageAllowance) GetAllowanceOk() (*PageAllowanceInfo, bool) {
	if o == nil || IsNil(o.Allowance) {
		return nil, false
	}
	return o.Allowance, true
}

// HasAllowance returns a boolean if a field has been set.
func (o *PageAllowance) HasAllowance() bool {
	if o != nil && !IsNil(o.Allowance) {
		return true
	}

	return false
}

// SetAllowance gets a reference to the given PageAllowanceInfo and assigns it to the Allowance field.
func (o *PageAllowance) SetAllowance(v PageAllowanceInfo) {
	o.Allowance = &v
}

// GetUsageHistory returns the UsageHistory field value if set, zero value otherwise.
func (o *PageAllowance) GetUsageHistory() []PageAllowanceUsageHistoryInner {
	if o == nil || IsNil(o.UsageHistory) {
		var ret []PageAllowanceUsageHistoryInner
		return ret
	}
	return o.UsageHistory
}

// GetUsageHistoryOk returns a tuple with the UsageHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageAllowance) GetUsageHistoryOk() ([]PageAllowanceUsageHistoryInner, bool) {
	if o == nil || IsNil(o.UsageHistory) {
		return nil, false
	}
	return o.UsageHistory, true
}

// HasUsageHistory returns a boolean if a field has been set.
func (o *PageAllowance) HasUsageHistory() bool {
	if o != nil && !IsNil(o.UsageHistory) {
		return true
	}

	return false
}

// SetUsageHistory gets a reference to the given []PageAllowanceUsageHistoryInner and assigns it to the UsageHistory field.
func (o *PageAllowance) SetUsageHistory(v []PageAllowanceUsageHistoryInner) {
	o.UsageHistory = v
}

func (o PageAllowance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageAllowance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Allowance) {
		toSerialize["allowance"] = o.Allowance
	}
	if !IsNil(o.UsageHistory) {
		toSerialize["usageHistory"] = o.UsageHistory
	}
	return toSerialize, nil
}

type NullablePageAllowance struct {
	value *PageAllowance
	isSet bool
}

func (v NullablePageAllowance) Get() *PageAllowance {
	return v.value
}

func (v *NullablePageAllowance) Set(val *PageAllowance) {
	v.value = val
	v.isSet = true
}

func (v NullablePageAllowance) IsSet() bool {
	return v.isSet
}

func (v *NullablePageAllowance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageAllowance(val *PageAllowance) *NullablePageAllowance {
	return &NullablePageAllowance{value: val, isSet: true}
}

func (v NullablePageAllowance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageAllowance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


