/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PageChange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageChange{}

// PageChange struct for PageChange
type PageChange struct {
	// Change identifier
	Id string `json:"id"`
	// Page identifier
	PageId string `json:"pageId"`
	// Project identifier
	ProjectId string `json:"projectId"`
	// Change status
	ChangeStatus string `json:"changeStatus"`
	// Page visibility
	Visibility string `json:"visibility"`
	// Previous scrape timestamp
	PreviousScrapeAt NullableTime `json:"previousScrapeAt,omitempty"`
	// Current scrape timestamp
	CurrentScrapeAt time.Time `json:"currentScrapeAt"`
	Page *PageChangePage `json:"page,omitempty"`
}

type _PageChange PageChange

// NewPageChange instantiates a new PageChange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageChange(id string, pageId string, projectId string, changeStatus string, visibility string, currentScrapeAt time.Time) *PageChange {
	this := PageChange{}
	this.Id = id
	this.PageId = pageId
	this.ProjectId = projectId
	this.ChangeStatus = changeStatus
	this.Visibility = visibility
	this.CurrentScrapeAt = currentScrapeAt
	return &this
}

// NewPageChangeWithDefaults instantiates a new PageChange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageChangeWithDefaults() *PageChange {
	this := PageChange{}
	return &this
}

// GetId returns the Id field value
func (o *PageChange) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PageChange) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PageChange) SetId(v string) {
	o.Id = v
}

// GetPageId returns the PageId field value
func (o *PageChange) GetPageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PageId
}

// GetPageIdOk returns a tuple with the PageId field value
// and a boolean to check if the value has been set.
func (o *PageChange) GetPageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageId, true
}

// SetPageId sets field value
func (o *PageChange) SetPageId(v string) {
	o.PageId = v
}

// GetProjectId returns the ProjectId field value
func (o *PageChange) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *PageChange) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *PageChange) SetProjectId(v string) {
	o.ProjectId = v
}

// GetChangeStatus returns the ChangeStatus field value
func (o *PageChange) GetChangeStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeStatus
}

// GetChangeStatusOk returns a tuple with the ChangeStatus field value
// and a boolean to check if the value has been set.
func (o *PageChange) GetChangeStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeStatus, true
}

// SetChangeStatus sets field value
func (o *PageChange) SetChangeStatus(v string) {
	o.ChangeStatus = v
}

// GetVisibility returns the Visibility field value
func (o *PageChange) GetVisibility() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *PageChange) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *PageChange) SetVisibility(v string) {
	o.Visibility = v
}

// GetPreviousScrapeAt returns the PreviousScrapeAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PageChange) GetPreviousScrapeAt() time.Time {
	if o == nil || IsNil(o.PreviousScrapeAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PreviousScrapeAt.Get()
}

// GetPreviousScrapeAtOk returns a tuple with the PreviousScrapeAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PageChange) GetPreviousScrapeAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousScrapeAt.Get(), o.PreviousScrapeAt.IsSet()
}

// HasPreviousScrapeAt returns a boolean if a field has been set.
func (o *PageChange) HasPreviousScrapeAt() bool {
	if o != nil && o.PreviousScrapeAt.IsSet() {
		return true
	}

	return false
}

// SetPreviousScrapeAt gets a reference to the given NullableTime and assigns it to the PreviousScrapeAt field.
func (o *PageChange) SetPreviousScrapeAt(v time.Time) {
	o.PreviousScrapeAt.Set(&v)
}
// SetPreviousScrapeAtNil sets the value for PreviousScrapeAt to be an explicit nil
func (o *PageChange) SetPreviousScrapeAtNil() {
	o.PreviousScrapeAt.Set(nil)
}

// UnsetPreviousScrapeAt ensures that no value is present for PreviousScrapeAt, not even an explicit nil
func (o *PageChange) UnsetPreviousScrapeAt() {
	o.PreviousScrapeAt.Unset()
}

// GetCurrentScrapeAt returns the CurrentScrapeAt field value
func (o *PageChange) GetCurrentScrapeAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CurrentScrapeAt
}

// GetCurrentScrapeAtOk returns a tuple with the CurrentScrapeAt field value
// and a boolean to check if the value has been set.
func (o *PageChange) GetCurrentScrapeAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentScrapeAt, true
}

// SetCurrentScrapeAt sets field value
func (o *PageChange) SetCurrentScrapeAt(v time.Time) {
	o.CurrentScrapeAt = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PageChange) GetPage() PageChangePage {
	if o == nil || IsNil(o.Page) {
		var ret PageChangePage
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageChange) GetPageOk() (*PageChangePage, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PageChange) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given PageChangePage and assigns it to the Page field.
func (o *PageChange) SetPage(v PageChangePage) {
	o.Page = &v
}

func (o PageChange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageChange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["pageId"] = o.PageId
	toSerialize["projectId"] = o.ProjectId
	toSerialize["changeStatus"] = o.ChangeStatus
	toSerialize["visibility"] = o.Visibility
	if o.PreviousScrapeAt.IsSet() {
		toSerialize["previousScrapeAt"] = o.PreviousScrapeAt.Get()
	}
	toSerialize["currentScrapeAt"] = o.CurrentScrapeAt
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

func (o *PageChange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"pageId",
		"projectId",
		"changeStatus",
		"visibility",
		"currentScrapeAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPageChange := _PageChange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPageChange)

	if err != nil {
		return err
	}

	*o = PageChange(varPageChange)

	return err
}

type NullablePageChange struct {
	value *PageChange
	isSet bool
}

func (v NullablePageChange) Get() *PageChange {
	return v.value
}

func (v *NullablePageChange) Set(val *PageChange) {
	v.value = val
	v.isSet = true
}

func (v NullablePageChange) IsSet() bool {
	return v.isSet
}

func (v *NullablePageChange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageChange(val *PageChange) *NullablePageChange {
	return &NullablePageChange{value: val, isSet: true}
}

func (v NullablePageChange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageChange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


