/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchSyncPagesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchSyncPagesRequest{}

// BatchSyncPagesRequest struct for BatchSyncPagesRequest
type BatchSyncPagesRequest struct {
	Pages []PageData `json:"pages"`
}

type _BatchSyncPagesRequest BatchSyncPagesRequest

// NewBatchSyncPagesRequest instantiates a new BatchSyncPagesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchSyncPagesRequest(pages []PageData) *BatchSyncPagesRequest {
	this := BatchSyncPagesRequest{}
	this.Pages = pages
	return &this
}

// NewBatchSyncPagesRequestWithDefaults instantiates a new BatchSyncPagesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchSyncPagesRequestWithDefaults() *BatchSyncPagesRequest {
	this := BatchSyncPagesRequest{}
	return &this
}

// GetPages returns the Pages field value
func (o *BatchSyncPagesRequest) GetPages() []PageData {
	if o == nil {
		var ret []PageData
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
func (o *BatchSyncPagesRequest) GetPagesOk() ([]PageData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pages, true
}

// SetPages sets field value
func (o *BatchSyncPagesRequest) SetPages(v []PageData) {
	o.Pages = v
}

func (o BatchSyncPagesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchSyncPagesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pages"] = o.Pages
	return toSerialize, nil
}

func (o *BatchSyncPagesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchSyncPagesRequest := _BatchSyncPagesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchSyncPagesRequest)

	if err != nil {
		return err
	}

	*o = BatchSyncPagesRequest(varBatchSyncPagesRequest)

	return err
}

type NullableBatchSyncPagesRequest struct {
	value *BatchSyncPagesRequest
	isSet bool
}

func (v NullableBatchSyncPagesRequest) Get() *BatchSyncPagesRequest {
	return v.value
}

func (v *NullableBatchSyncPagesRequest) Set(val *BatchSyncPagesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchSyncPagesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchSyncPagesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchSyncPagesRequest(val *BatchSyncPagesRequest) *NullableBatchSyncPagesRequest {
	return &NullableBatchSyncPagesRequest{value: val, isSet: true}
}

func (v NullableBatchSyncPagesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchSyncPagesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


