/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the GetUserInfo200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserInfo200ResponseLinks{}

// GetUserInfo200ResponseLinks struct for GetUserInfo200ResponseLinks
type GetUserInfo200ResponseLinks struct {
	Total *float32 `json:"total,omitempty"`
	Used *float32 `json:"used,omitempty"`
	Remaining *float32 `json:"remaining,omitempty"`
}

// NewGetUserInfo200ResponseLinks instantiates a new GetUserInfo200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserInfo200ResponseLinks() *GetUserInfo200ResponseLinks {
	this := GetUserInfo200ResponseLinks{}
	return &this
}

// NewGetUserInfo200ResponseLinksWithDefaults instantiates a new GetUserInfo200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserInfo200ResponseLinksWithDefaults() *GetUserInfo200ResponseLinks {
	this := GetUserInfo200ResponseLinks{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetUserInfo200ResponseLinks) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200ResponseLinks) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetUserInfo200ResponseLinks) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *GetUserInfo200ResponseLinks) SetTotal(v float32) {
	o.Total = &v
}

// GetUsed returns the Used field value if set, zero value otherwise.
func (o *GetUserInfo200ResponseLinks) GetUsed() float32 {
	if o == nil || IsNil(o.Used) {
		var ret float32
		return ret
	}
	return *o.Used
}

// GetUsedOk returns a tuple with the Used field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200ResponseLinks) GetUsedOk() (*float32, bool) {
	if o == nil || IsNil(o.Used) {
		return nil, false
	}
	return o.Used, true
}

// HasUsed returns a boolean if a field has been set.
func (o *GetUserInfo200ResponseLinks) HasUsed() bool {
	if o != nil && !IsNil(o.Used) {
		return true
	}

	return false
}

// SetUsed gets a reference to the given float32 and assigns it to the Used field.
func (o *GetUserInfo200ResponseLinks) SetUsed(v float32) {
	o.Used = &v
}

// GetRemaining returns the Remaining field value if set, zero value otherwise.
func (o *GetUserInfo200ResponseLinks) GetRemaining() float32 {
	if o == nil || IsNil(o.Remaining) {
		var ret float32
		return ret
	}
	return *o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200ResponseLinks) GetRemainingOk() (*float32, bool) {
	if o == nil || IsNil(o.Remaining) {
		return nil, false
	}
	return o.Remaining, true
}

// HasRemaining returns a boolean if a field has been set.
func (o *GetUserInfo200ResponseLinks) HasRemaining() bool {
	if o != nil && !IsNil(o.Remaining) {
		return true
	}

	return false
}

// SetRemaining gets a reference to the given float32 and assigns it to the Remaining field.
func (o *GetUserInfo200ResponseLinks) SetRemaining(v float32) {
	o.Remaining = &v
}

func (o GetUserInfo200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserInfo200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Used) {
		toSerialize["used"] = o.Used
	}
	if !IsNil(o.Remaining) {
		toSerialize["remaining"] = o.Remaining
	}
	return toSerialize, nil
}

type NullableGetUserInfo200ResponseLinks struct {
	value *GetUserInfo200ResponseLinks
	isSet bool
}

func (v NullableGetUserInfo200ResponseLinks) Get() *GetUserInfo200ResponseLinks {
	return v.value
}

func (v *NullableGetUserInfo200ResponseLinks) Set(val *GetUserInfo200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserInfo200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserInfo200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserInfo200ResponseLinks(val *GetUserInfo200ResponseLinks) *NullableGetUserInfo200ResponseLinks {
	return &NullableGetUserInfo200ResponseLinks{value: val, isSet: true}
}

func (v NullableGetUserInfo200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserInfo200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


