/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Project type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Project{}

// Project struct for Project
type Project struct {
	// Unique project identifier
	Id string `json:"id"`
	// Project name
	Name string `json:"name"`
	// Website domain URL
	Domain string `json:"domain"`
	// User who owns the project
	UserId string `json:"userId"`
	// Natural language prompt for crawling
	Prompt *string `json:"prompt,omitempty"`
	// Search query for targeted crawling
	SearchQuery *string `json:"searchQuery,omitempty"`
	// How to handle sitemaps
	SitemapMode *string `json:"sitemapMode,omitempty"`
	// Whether to include subdomains
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty"`
	// Whether to ignore URL query parameters
	IgnoreQueryParams *bool `json:"ignoreQueryParams,omitempty"`
	// Maximum crawl depth
	MaxDiscoveryDepth *int32 `json:"maxDiscoveryDepth,omitempty"`
	// Paths to exclude from crawling
	ExcludePaths []string `json:"excludePaths,omitempty"`
	// Specific paths to include
	IncludePaths []string `json:"includePaths,omitempty"`
	// Whether to crawl the entire domain
	CrawlEntireDomain *bool `json:"crawlEntireDomain,omitempty"`
	// Whether to allow external links
	AllowExternalLinks *bool `json:"allowExternalLinks,omitempty"`
	// Maximum number of pages to crawl
	MaxPages *int32 `json:"maxPages,omitempty"`
	// Delay between crawl requests (ms)
	CrawlDelay *int32 `json:"crawlDelay,omitempty"`
	// Maximum concurrent crawl requests
	CrawlMaxConcurrency *int32 `json:"crawlMaxConcurrency,omitempty"`
	// Whether to extract only main content
	OnlyMainContent *bool `json:"onlyMainContent,omitempty"`
	// Custom headers for crawling
	CustomHeaders *map[string]string `json:"customHeaders,omitempty"`
	// Wait time for page load (ms)
	WaitFor *int32 `json:"waitFor,omitempty"`
	// Whether to block ads
	BlockAds *bool `json:"blockAds,omitempty"`
	// Proxy mode for crawling
	ProxyMode *string `json:"proxyMode,omitempty"`
	// Whether to use AI reranking
	UseReranking *bool `json:"useReranking,omitempty"`
	// Whether to enable change tracking
	EnableChangeTracking *bool `json:"enableChangeTracking,omitempty"`
	// Project creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
	Count *ProjectCount `json:"_count,omitempty"`
}

type _Project Project

// NewProject instantiates a new Project object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProject(id string, name string, domain string, userId string, createdAt time.Time, updatedAt time.Time) *Project {
	this := Project{}
	this.Id = id
	this.Name = name
	this.Domain = domain
	this.UserId = userId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewProjectWithDefaults instantiates a new Project object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectWithDefaults() *Project {
	this := Project{}
	return &this
}

// GetId returns the Id field value
func (o *Project) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Project) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Project) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Project) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Project) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Project) SetName(v string) {
	o.Name = v
}

// GetDomain returns the Domain field value
func (o *Project) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *Project) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *Project) SetDomain(v string) {
	o.Domain = v
}

// GetUserId returns the UserId field value
func (o *Project) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Project) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Project) SetUserId(v string) {
	o.UserId = v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *Project) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *Project) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *Project) SetPrompt(v string) {
	o.Prompt = &v
}

// GetSearchQuery returns the SearchQuery field value if set, zero value otherwise.
func (o *Project) GetSearchQuery() string {
	if o == nil || IsNil(o.SearchQuery) {
		var ret string
		return ret
	}
	return *o.SearchQuery
}

// GetSearchQueryOk returns a tuple with the SearchQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetSearchQueryOk() (*string, bool) {
	if o == nil || IsNil(o.SearchQuery) {
		return nil, false
	}
	return o.SearchQuery, true
}

// HasSearchQuery returns a boolean if a field has been set.
func (o *Project) HasSearchQuery() bool {
	if o != nil && !IsNil(o.SearchQuery) {
		return true
	}

	return false
}

// SetSearchQuery gets a reference to the given string and assigns it to the SearchQuery field.
func (o *Project) SetSearchQuery(v string) {
	o.SearchQuery = &v
}

// GetSitemapMode returns the SitemapMode field value if set, zero value otherwise.
func (o *Project) GetSitemapMode() string {
	if o == nil || IsNil(o.SitemapMode) {
		var ret string
		return ret
	}
	return *o.SitemapMode
}

// GetSitemapModeOk returns a tuple with the SitemapMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetSitemapModeOk() (*string, bool) {
	if o == nil || IsNil(o.SitemapMode) {
		return nil, false
	}
	return o.SitemapMode, true
}

// HasSitemapMode returns a boolean if a field has been set.
func (o *Project) HasSitemapMode() bool {
	if o != nil && !IsNil(o.SitemapMode) {
		return true
	}

	return false
}

// SetSitemapMode gets a reference to the given string and assigns it to the SitemapMode field.
func (o *Project) SetSitemapMode(v string) {
	o.SitemapMode = &v
}

// GetIncludeSubdomains returns the IncludeSubdomains field value if set, zero value otherwise.
func (o *Project) GetIncludeSubdomains() bool {
	if o == nil || IsNil(o.IncludeSubdomains) {
		var ret bool
		return ret
	}
	return *o.IncludeSubdomains
}

// GetIncludeSubdomainsOk returns a tuple with the IncludeSubdomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetIncludeSubdomainsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeSubdomains) {
		return nil, false
	}
	return o.IncludeSubdomains, true
}

// HasIncludeSubdomains returns a boolean if a field has been set.
func (o *Project) HasIncludeSubdomains() bool {
	if o != nil && !IsNil(o.IncludeSubdomains) {
		return true
	}

	return false
}

// SetIncludeSubdomains gets a reference to the given bool and assigns it to the IncludeSubdomains field.
func (o *Project) SetIncludeSubdomains(v bool) {
	o.IncludeSubdomains = &v
}

// GetIgnoreQueryParams returns the IgnoreQueryParams field value if set, zero value otherwise.
func (o *Project) GetIgnoreQueryParams() bool {
	if o == nil || IsNil(o.IgnoreQueryParams) {
		var ret bool
		return ret
	}
	return *o.IgnoreQueryParams
}

// GetIgnoreQueryParamsOk returns a tuple with the IgnoreQueryParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetIgnoreQueryParamsOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreQueryParams) {
		return nil, false
	}
	return o.IgnoreQueryParams, true
}

// HasIgnoreQueryParams returns a boolean if a field has been set.
func (o *Project) HasIgnoreQueryParams() bool {
	if o != nil && !IsNil(o.IgnoreQueryParams) {
		return true
	}

	return false
}

// SetIgnoreQueryParams gets a reference to the given bool and assigns it to the IgnoreQueryParams field.
func (o *Project) SetIgnoreQueryParams(v bool) {
	o.IgnoreQueryParams = &v
}

// GetMaxDiscoveryDepth returns the MaxDiscoveryDepth field value if set, zero value otherwise.
func (o *Project) GetMaxDiscoveryDepth() int32 {
	if o == nil || IsNil(o.MaxDiscoveryDepth) {
		var ret int32
		return ret
	}
	return *o.MaxDiscoveryDepth
}

// GetMaxDiscoveryDepthOk returns a tuple with the MaxDiscoveryDepth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetMaxDiscoveryDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDiscoveryDepth) {
		return nil, false
	}
	return o.MaxDiscoveryDepth, true
}

// HasMaxDiscoveryDepth returns a boolean if a field has been set.
func (o *Project) HasMaxDiscoveryDepth() bool {
	if o != nil && !IsNil(o.MaxDiscoveryDepth) {
		return true
	}

	return false
}

// SetMaxDiscoveryDepth gets a reference to the given int32 and assigns it to the MaxDiscoveryDepth field.
func (o *Project) SetMaxDiscoveryDepth(v int32) {
	o.MaxDiscoveryDepth = &v
}

// GetExcludePaths returns the ExcludePaths field value if set, zero value otherwise.
func (o *Project) GetExcludePaths() []string {
	if o == nil || IsNil(o.ExcludePaths) {
		var ret []string
		return ret
	}
	return o.ExcludePaths
}

// GetExcludePathsOk returns a tuple with the ExcludePaths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetExcludePathsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludePaths) {
		return nil, false
	}
	return o.ExcludePaths, true
}

// HasExcludePaths returns a boolean if a field has been set.
func (o *Project) HasExcludePaths() bool {
	if o != nil && !IsNil(o.ExcludePaths) {
		return true
	}

	return false
}

// SetExcludePaths gets a reference to the given []string and assigns it to the ExcludePaths field.
func (o *Project) SetExcludePaths(v []string) {
	o.ExcludePaths = v
}

// GetIncludePaths returns the IncludePaths field value if set, zero value otherwise.
func (o *Project) GetIncludePaths() []string {
	if o == nil || IsNil(o.IncludePaths) {
		var ret []string
		return ret
	}
	return o.IncludePaths
}

// GetIncludePathsOk returns a tuple with the IncludePaths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetIncludePathsOk() ([]string, bool) {
	if o == nil || IsNil(o.IncludePaths) {
		return nil, false
	}
	return o.IncludePaths, true
}

// HasIncludePaths returns a boolean if a field has been set.
func (o *Project) HasIncludePaths() bool {
	if o != nil && !IsNil(o.IncludePaths) {
		return true
	}

	return false
}

// SetIncludePaths gets a reference to the given []string and assigns it to the IncludePaths field.
func (o *Project) SetIncludePaths(v []string) {
	o.IncludePaths = v
}

// GetCrawlEntireDomain returns the CrawlEntireDomain field value if set, zero value otherwise.
func (o *Project) GetCrawlEntireDomain() bool {
	if o == nil || IsNil(o.CrawlEntireDomain) {
		var ret bool
		return ret
	}
	return *o.CrawlEntireDomain
}

// GetCrawlEntireDomainOk returns a tuple with the CrawlEntireDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetCrawlEntireDomainOk() (*bool, bool) {
	if o == nil || IsNil(o.CrawlEntireDomain) {
		return nil, false
	}
	return o.CrawlEntireDomain, true
}

// HasCrawlEntireDomain returns a boolean if a field has been set.
func (o *Project) HasCrawlEntireDomain() bool {
	if o != nil && !IsNil(o.CrawlEntireDomain) {
		return true
	}

	return false
}

// SetCrawlEntireDomain gets a reference to the given bool and assigns it to the CrawlEntireDomain field.
func (o *Project) SetCrawlEntireDomain(v bool) {
	o.CrawlEntireDomain = &v
}

// GetAllowExternalLinks returns the AllowExternalLinks field value if set, zero value otherwise.
func (o *Project) GetAllowExternalLinks() bool {
	if o == nil || IsNil(o.AllowExternalLinks) {
		var ret bool
		return ret
	}
	return *o.AllowExternalLinks
}

// GetAllowExternalLinksOk returns a tuple with the AllowExternalLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetAllowExternalLinksOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowExternalLinks) {
		return nil, false
	}
	return o.AllowExternalLinks, true
}

// HasAllowExternalLinks returns a boolean if a field has been set.
func (o *Project) HasAllowExternalLinks() bool {
	if o != nil && !IsNil(o.AllowExternalLinks) {
		return true
	}

	return false
}

// SetAllowExternalLinks gets a reference to the given bool and assigns it to the AllowExternalLinks field.
func (o *Project) SetAllowExternalLinks(v bool) {
	o.AllowExternalLinks = &v
}

// GetMaxPages returns the MaxPages field value if set, zero value otherwise.
func (o *Project) GetMaxPages() int32 {
	if o == nil || IsNil(o.MaxPages) {
		var ret int32
		return ret
	}
	return *o.MaxPages
}

// GetMaxPagesOk returns a tuple with the MaxPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetMaxPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxPages) {
		return nil, false
	}
	return o.MaxPages, true
}

// HasMaxPages returns a boolean if a field has been set.
func (o *Project) HasMaxPages() bool {
	if o != nil && !IsNil(o.MaxPages) {
		return true
	}

	return false
}

// SetMaxPages gets a reference to the given int32 and assigns it to the MaxPages field.
func (o *Project) SetMaxPages(v int32) {
	o.MaxPages = &v
}

// GetCrawlDelay returns the CrawlDelay field value if set, zero value otherwise.
func (o *Project) GetCrawlDelay() int32 {
	if o == nil || IsNil(o.CrawlDelay) {
		var ret int32
		return ret
	}
	return *o.CrawlDelay
}

// GetCrawlDelayOk returns a tuple with the CrawlDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetCrawlDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.CrawlDelay) {
		return nil, false
	}
	return o.CrawlDelay, true
}

// HasCrawlDelay returns a boolean if a field has been set.
func (o *Project) HasCrawlDelay() bool {
	if o != nil && !IsNil(o.CrawlDelay) {
		return true
	}

	return false
}

// SetCrawlDelay gets a reference to the given int32 and assigns it to the CrawlDelay field.
func (o *Project) SetCrawlDelay(v int32) {
	o.CrawlDelay = &v
}

// GetCrawlMaxConcurrency returns the CrawlMaxConcurrency field value if set, zero value otherwise.
func (o *Project) GetCrawlMaxConcurrency() int32 {
	if o == nil || IsNil(o.CrawlMaxConcurrency) {
		var ret int32
		return ret
	}
	return *o.CrawlMaxConcurrency
}

// GetCrawlMaxConcurrencyOk returns a tuple with the CrawlMaxConcurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetCrawlMaxConcurrencyOk() (*int32, bool) {
	if o == nil || IsNil(o.CrawlMaxConcurrency) {
		return nil, false
	}
	return o.CrawlMaxConcurrency, true
}

// HasCrawlMaxConcurrency returns a boolean if a field has been set.
func (o *Project) HasCrawlMaxConcurrency() bool {
	if o != nil && !IsNil(o.CrawlMaxConcurrency) {
		return true
	}

	return false
}

// SetCrawlMaxConcurrency gets a reference to the given int32 and assigns it to the CrawlMaxConcurrency field.
func (o *Project) SetCrawlMaxConcurrency(v int32) {
	o.CrawlMaxConcurrency = &v
}

// GetOnlyMainContent returns the OnlyMainContent field value if set, zero value otherwise.
func (o *Project) GetOnlyMainContent() bool {
	if o == nil || IsNil(o.OnlyMainContent) {
		var ret bool
		return ret
	}
	return *o.OnlyMainContent
}

// GetOnlyMainContentOk returns a tuple with the OnlyMainContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetOnlyMainContentOk() (*bool, bool) {
	if o == nil || IsNil(o.OnlyMainContent) {
		return nil, false
	}
	return o.OnlyMainContent, true
}

// HasOnlyMainContent returns a boolean if a field has been set.
func (o *Project) HasOnlyMainContent() bool {
	if o != nil && !IsNil(o.OnlyMainContent) {
		return true
	}

	return false
}

// SetOnlyMainContent gets a reference to the given bool and assigns it to the OnlyMainContent field.
func (o *Project) SetOnlyMainContent(v bool) {
	o.OnlyMainContent = &v
}

// GetCustomHeaders returns the CustomHeaders field value if set, zero value otherwise.
func (o *Project) GetCustomHeaders() map[string]string {
	if o == nil || IsNil(o.CustomHeaders) {
		var ret map[string]string
		return ret
	}
	return *o.CustomHeaders
}

// GetCustomHeadersOk returns a tuple with the CustomHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetCustomHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.CustomHeaders) {
		return nil, false
	}
	return o.CustomHeaders, true
}

// HasCustomHeaders returns a boolean if a field has been set.
func (o *Project) HasCustomHeaders() bool {
	if o != nil && !IsNil(o.CustomHeaders) {
		return true
	}

	return false
}

// SetCustomHeaders gets a reference to the given map[string]string and assigns it to the CustomHeaders field.
func (o *Project) SetCustomHeaders(v map[string]string) {
	o.CustomHeaders = &v
}

// GetWaitFor returns the WaitFor field value if set, zero value otherwise.
func (o *Project) GetWaitFor() int32 {
	if o == nil || IsNil(o.WaitFor) {
		var ret int32
		return ret
	}
	return *o.WaitFor
}

// GetWaitForOk returns a tuple with the WaitFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetWaitForOk() (*int32, bool) {
	if o == nil || IsNil(o.WaitFor) {
		return nil, false
	}
	return o.WaitFor, true
}

// HasWaitFor returns a boolean if a field has been set.
func (o *Project) HasWaitFor() bool {
	if o != nil && !IsNil(o.WaitFor) {
		return true
	}

	return false
}

// SetWaitFor gets a reference to the given int32 and assigns it to the WaitFor field.
func (o *Project) SetWaitFor(v int32) {
	o.WaitFor = &v
}

// GetBlockAds returns the BlockAds field value if set, zero value otherwise.
func (o *Project) GetBlockAds() bool {
	if o == nil || IsNil(o.BlockAds) {
		var ret bool
		return ret
	}
	return *o.BlockAds
}

// GetBlockAdsOk returns a tuple with the BlockAds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetBlockAdsOk() (*bool, bool) {
	if o == nil || IsNil(o.BlockAds) {
		return nil, false
	}
	return o.BlockAds, true
}

// HasBlockAds returns a boolean if a field has been set.
func (o *Project) HasBlockAds() bool {
	if o != nil && !IsNil(o.BlockAds) {
		return true
	}

	return false
}

// SetBlockAds gets a reference to the given bool and assigns it to the BlockAds field.
func (o *Project) SetBlockAds(v bool) {
	o.BlockAds = &v
}

// GetProxyMode returns the ProxyMode field value if set, zero value otherwise.
func (o *Project) GetProxyMode() string {
	if o == nil || IsNil(o.ProxyMode) {
		var ret string
		return ret
	}
	return *o.ProxyMode
}

// GetProxyModeOk returns a tuple with the ProxyMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetProxyModeOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyMode) {
		return nil, false
	}
	return o.ProxyMode, true
}

// HasProxyMode returns a boolean if a field has been set.
func (o *Project) HasProxyMode() bool {
	if o != nil && !IsNil(o.ProxyMode) {
		return true
	}

	return false
}

// SetProxyMode gets a reference to the given string and assigns it to the ProxyMode field.
func (o *Project) SetProxyMode(v string) {
	o.ProxyMode = &v
}

// GetUseReranking returns the UseReranking field value if set, zero value otherwise.
func (o *Project) GetUseReranking() bool {
	if o == nil || IsNil(o.UseReranking) {
		var ret bool
		return ret
	}
	return *o.UseReranking
}

// GetUseRerankingOk returns a tuple with the UseReranking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetUseRerankingOk() (*bool, bool) {
	if o == nil || IsNil(o.UseReranking) {
		return nil, false
	}
	return o.UseReranking, true
}

// HasUseReranking returns a boolean if a field has been set.
func (o *Project) HasUseReranking() bool {
	if o != nil && !IsNil(o.UseReranking) {
		return true
	}

	return false
}

// SetUseReranking gets a reference to the given bool and assigns it to the UseReranking field.
func (o *Project) SetUseReranking(v bool) {
	o.UseReranking = &v
}

// GetEnableChangeTracking returns the EnableChangeTracking field value if set, zero value otherwise.
func (o *Project) GetEnableChangeTracking() bool {
	if o == nil || IsNil(o.EnableChangeTracking) {
		var ret bool
		return ret
	}
	return *o.EnableChangeTracking
}

// GetEnableChangeTrackingOk returns a tuple with the EnableChangeTracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetEnableChangeTrackingOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableChangeTracking) {
		return nil, false
	}
	return o.EnableChangeTracking, true
}

// HasEnableChangeTracking returns a boolean if a field has been set.
func (o *Project) HasEnableChangeTracking() bool {
	if o != nil && !IsNil(o.EnableChangeTracking) {
		return true
	}

	return false
}

// SetEnableChangeTracking gets a reference to the given bool and assigns it to the EnableChangeTracking field.
func (o *Project) SetEnableChangeTracking(v bool) {
	o.EnableChangeTracking = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Project) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Project) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Project) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Project) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Project) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Project) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *Project) GetCount() ProjectCount {
	if o == nil || IsNil(o.Count) {
		var ret ProjectCount
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetCountOk() (*ProjectCount, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *Project) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given ProjectCount and assigns it to the Count field.
func (o *Project) SetCount(v ProjectCount) {
	o.Count = &v
}

func (o Project) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Project) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["domain"] = o.Domain
	toSerialize["userId"] = o.UserId
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.SearchQuery) {
		toSerialize["searchQuery"] = o.SearchQuery
	}
	if !IsNil(o.SitemapMode) {
		toSerialize["sitemapMode"] = o.SitemapMode
	}
	if !IsNil(o.IncludeSubdomains) {
		toSerialize["includeSubdomains"] = o.IncludeSubdomains
	}
	if !IsNil(o.IgnoreQueryParams) {
		toSerialize["ignoreQueryParams"] = o.IgnoreQueryParams
	}
	if !IsNil(o.MaxDiscoveryDepth) {
		toSerialize["maxDiscoveryDepth"] = o.MaxDiscoveryDepth
	}
	if !IsNil(o.ExcludePaths) {
		toSerialize["excludePaths"] = o.ExcludePaths
	}
	if !IsNil(o.IncludePaths) {
		toSerialize["includePaths"] = o.IncludePaths
	}
	if !IsNil(o.CrawlEntireDomain) {
		toSerialize["crawlEntireDomain"] = o.CrawlEntireDomain
	}
	if !IsNil(o.AllowExternalLinks) {
		toSerialize["allowExternalLinks"] = o.AllowExternalLinks
	}
	if !IsNil(o.MaxPages) {
		toSerialize["maxPages"] = o.MaxPages
	}
	if !IsNil(o.CrawlDelay) {
		toSerialize["crawlDelay"] = o.CrawlDelay
	}
	if !IsNil(o.CrawlMaxConcurrency) {
		toSerialize["crawlMaxConcurrency"] = o.CrawlMaxConcurrency
	}
	if !IsNil(o.OnlyMainContent) {
		toSerialize["onlyMainContent"] = o.OnlyMainContent
	}
	if !IsNil(o.CustomHeaders) {
		toSerialize["customHeaders"] = o.CustomHeaders
	}
	if !IsNil(o.WaitFor) {
		toSerialize["waitFor"] = o.WaitFor
	}
	if !IsNil(o.BlockAds) {
		toSerialize["blockAds"] = o.BlockAds
	}
	if !IsNil(o.ProxyMode) {
		toSerialize["proxyMode"] = o.ProxyMode
	}
	if !IsNil(o.UseReranking) {
		toSerialize["useReranking"] = o.UseReranking
	}
	if !IsNil(o.EnableChangeTracking) {
		toSerialize["enableChangeTracking"] = o.EnableChangeTracking
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if !IsNil(o.Count) {
		toSerialize["_count"] = o.Count
	}
	return toSerialize, nil
}

func (o *Project) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"domain",
		"userId",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProject := _Project{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProject)

	if err != nil {
		return err
	}

	*o = Project(varProject)

	return err
}

type NullableProject struct {
	value *Project
	isSet bool
}

func (v NullableProject) Get() *Project {
	return v.value
}

func (v *NullableProject) Set(val *Project) {
	v.value = val
	v.isSet = true
}

func (v NullableProject) IsSet() bool {
	return v.isSet
}

func (v *NullableProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProject(val *Project) *NullableProject {
	return &NullableProject{value: val, isSet: true}
}

func (v NullableProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


