/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the GetUserInfo200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserInfo200Response{}

// GetUserInfo200Response struct for GetUserInfo200Response
type GetUserInfo200Response struct {
	Success *bool `json:"success,omitempty"`
	User *GetUserInfo200ResponseUser `json:"user,omitempty"`
	Links *GetUserInfo200ResponseLinks `json:"links,omitempty"`
	ProjectsCount *int32 `json:"projectsCount,omitempty"`
	// Recent usage (pages indexed in last 30 days)
	RecentUsage *float32 `json:"recentUsage,omitempty"`
}

// NewGetUserInfo200Response instantiates a new GetUserInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserInfo200Response() *GetUserInfo200Response {
	this := GetUserInfo200Response{}
	return &this
}

// NewGetUserInfo200ResponseWithDefaults instantiates a new GetUserInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserInfo200ResponseWithDefaults() *GetUserInfo200Response {
	this := GetUserInfo200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetUserInfo200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetUserInfo200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetUserInfo200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *GetUserInfo200Response) GetUser() GetUserInfo200ResponseUser {
	if o == nil || IsNil(o.User) {
		var ret GetUserInfo200ResponseUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200Response) GetUserOk() (*GetUserInfo200ResponseUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *GetUserInfo200Response) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given GetUserInfo200ResponseUser and assigns it to the User field.
func (o *GetUserInfo200Response) SetUser(v GetUserInfo200ResponseUser) {
	o.User = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetUserInfo200Response) GetLinks() GetUserInfo200ResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret GetUserInfo200ResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200Response) GetLinksOk() (*GetUserInfo200ResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetUserInfo200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given GetUserInfo200ResponseLinks and assigns it to the Links field.
func (o *GetUserInfo200Response) SetLinks(v GetUserInfo200ResponseLinks) {
	o.Links = &v
}

// GetProjectsCount returns the ProjectsCount field value if set, zero value otherwise.
func (o *GetUserInfo200Response) GetProjectsCount() int32 {
	if o == nil || IsNil(o.ProjectsCount) {
		var ret int32
		return ret
	}
	return *o.ProjectsCount
}

// GetProjectsCountOk returns a tuple with the ProjectsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200Response) GetProjectsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectsCount) {
		return nil, false
	}
	return o.ProjectsCount, true
}

// HasProjectsCount returns a boolean if a field has been set.
func (o *GetUserInfo200Response) HasProjectsCount() bool {
	if o != nil && !IsNil(o.ProjectsCount) {
		return true
	}

	return false
}

// SetProjectsCount gets a reference to the given int32 and assigns it to the ProjectsCount field.
func (o *GetUserInfo200Response) SetProjectsCount(v int32) {
	o.ProjectsCount = &v
}

// GetRecentUsage returns the RecentUsage field value if set, zero value otherwise.
func (o *GetUserInfo200Response) GetRecentUsage() float32 {
	if o == nil || IsNil(o.RecentUsage) {
		var ret float32
		return ret
	}
	return *o.RecentUsage
}

// GetRecentUsageOk returns a tuple with the RecentUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInfo200Response) GetRecentUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.RecentUsage) {
		return nil, false
	}
	return o.RecentUsage, true
}

// HasRecentUsage returns a boolean if a field has been set.
func (o *GetUserInfo200Response) HasRecentUsage() bool {
	if o != nil && !IsNil(o.RecentUsage) {
		return true
	}

	return false
}

// SetRecentUsage gets a reference to the given float32 and assigns it to the RecentUsage field.
func (o *GetUserInfo200Response) SetRecentUsage(v float32) {
	o.RecentUsage = &v
}

func (o GetUserInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserInfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.ProjectsCount) {
		toSerialize["projectsCount"] = o.ProjectsCount
	}
	if !IsNil(o.RecentUsage) {
		toSerialize["recentUsage"] = o.RecentUsage
	}
	return toSerialize, nil
}

type NullableGetUserInfo200Response struct {
	value *GetUserInfo200Response
	isSet bool
}

func (v NullableGetUserInfo200Response) Get() *GetUserInfo200Response {
	return v.value
}

func (v *NullableGetUserInfo200Response) Set(val *GetUserInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserInfo200Response(val *GetUserInfo200Response) *NullableGetUserInfo200Response {
	return &NullableGetUserInfo200Response{value: val, isSet: true}
}

func (v NullableGetUserInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


