/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 

API version: 1.2.0
Contact: support@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AutoRechargeSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoRechargeSettings{}

// AutoRechargeSettings struct for AutoRechargeSettings
type AutoRechargeSettings struct {
	// Whether auto-recharge is enabled
	Enabled bool `json:"enabled"`
	// Credit threshold for auto-recharge
	Threshold float32 `json:"threshold"`
	// Amount to recharge
	Amount float32 `json:"amount"`
}

type _AutoRechargeSettings AutoRechargeSettings

// NewAutoRechargeSettings instantiates a new AutoRechargeSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoRechargeSettings(enabled bool, threshold float32, amount float32) *AutoRechargeSettings {
	this := AutoRechargeSettings{}
	this.Enabled = enabled
	this.Threshold = threshold
	this.Amount = amount
	return &this
}

// NewAutoRechargeSettingsWithDefaults instantiates a new AutoRechargeSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoRechargeSettingsWithDefaults() *AutoRechargeSettings {
	this := AutoRechargeSettings{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *AutoRechargeSettings) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeSettings) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AutoRechargeSettings) SetEnabled(v bool) {
	o.Enabled = v
}

// GetThreshold returns the Threshold field value
func (o *AutoRechargeSettings) GetThreshold() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeSettings) GetThresholdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *AutoRechargeSettings) SetThreshold(v float32) {
	o.Threshold = v
}

// GetAmount returns the Amount field value
func (o *AutoRechargeSettings) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeSettings) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AutoRechargeSettings) SetAmount(v float32) {
	o.Amount = v
}

func (o AutoRechargeSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoRechargeSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["threshold"] = o.Threshold
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *AutoRechargeSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"threshold",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutoRechargeSettings := _AutoRechargeSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAutoRechargeSettings)

	if err != nil {
		return err
	}

	*o = AutoRechargeSettings(varAutoRechargeSettings)

	return err
}

type NullableAutoRechargeSettings struct {
	value *AutoRechargeSettings
	isSet bool
}

func (v NullableAutoRechargeSettings) Get() *AutoRechargeSettings {
	return v.value
}

func (v *NullableAutoRechargeSettings) Set(val *AutoRechargeSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoRechargeSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoRechargeSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoRechargeSettings(val *AutoRechargeSettings) *NullableAutoRechargeSettings {
	return &NullableAutoRechargeSettings{value: val, isSet: true}
}

func (v NullableAutoRechargeSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoRechargeSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


