/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the ProjectAnalyticsSuggestionStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAnalyticsSuggestionStats{}

// ProjectAnalyticsSuggestionStats struct for ProjectAnalyticsSuggestionStats
type ProjectAnalyticsSuggestionStats struct {
	Total *int32 `json:"total,omitempty"`
	Pending *int32 `json:"pending,omitempty"`
	Approved *int32 `json:"approved,omitempty"`
	Rejected *int32 `json:"rejected,omitempty"`
	Implemented *int32 `json:"implemented,omitempty"`
	AcceptanceRate *float32 `json:"acceptanceRate,omitempty"`
	ImplementationRate *float32 `json:"implementationRate,omitempty"`
	AvgRelevanceScore *float32 `json:"avgRelevanceScore,omitempty"`
	RelevanceScoreDistribution map[string]interface{} `json:"relevanceScoreDistribution,omitempty"`
}

// NewProjectAnalyticsSuggestionStats instantiates a new ProjectAnalyticsSuggestionStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAnalyticsSuggestionStats() *ProjectAnalyticsSuggestionStats {
	this := ProjectAnalyticsSuggestionStats{}
	return &this
}

// NewProjectAnalyticsSuggestionStatsWithDefaults instantiates a new ProjectAnalyticsSuggestionStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAnalyticsSuggestionStatsWithDefaults() *ProjectAnalyticsSuggestionStats {
	this := ProjectAnalyticsSuggestionStats{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ProjectAnalyticsSuggestionStats) SetTotal(v int32) {
	o.Total = &v
}

// GetPending returns the Pending field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetPending() int32 {
	if o == nil || IsNil(o.Pending) {
		var ret int32
		return ret
	}
	return *o.Pending
}

// GetPendingOk returns a tuple with the Pending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetPendingOk() (*int32, bool) {
	if o == nil || IsNil(o.Pending) {
		return nil, false
	}
	return o.Pending, true
}

// HasPending returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasPending() bool {
	if o != nil && !IsNil(o.Pending) {
		return true
	}

	return false
}

// SetPending gets a reference to the given int32 and assigns it to the Pending field.
func (o *ProjectAnalyticsSuggestionStats) SetPending(v int32) {
	o.Pending = &v
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetApproved() int32 {
	if o == nil || IsNil(o.Approved) {
		var ret int32
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetApprovedOk() (*int32, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given int32 and assigns it to the Approved field.
func (o *ProjectAnalyticsSuggestionStats) SetApproved(v int32) {
	o.Approved = &v
}

// GetRejected returns the Rejected field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetRejected() int32 {
	if o == nil || IsNil(o.Rejected) {
		var ret int32
		return ret
	}
	return *o.Rejected
}

// GetRejectedOk returns a tuple with the Rejected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetRejectedOk() (*int32, bool) {
	if o == nil || IsNil(o.Rejected) {
		return nil, false
	}
	return o.Rejected, true
}

// HasRejected returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasRejected() bool {
	if o != nil && !IsNil(o.Rejected) {
		return true
	}

	return false
}

// SetRejected gets a reference to the given int32 and assigns it to the Rejected field.
func (o *ProjectAnalyticsSuggestionStats) SetRejected(v int32) {
	o.Rejected = &v
}

// GetImplemented returns the Implemented field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetImplemented() int32 {
	if o == nil || IsNil(o.Implemented) {
		var ret int32
		return ret
	}
	return *o.Implemented
}

// GetImplementedOk returns a tuple with the Implemented field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetImplementedOk() (*int32, bool) {
	if o == nil || IsNil(o.Implemented) {
		return nil, false
	}
	return o.Implemented, true
}

// HasImplemented returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasImplemented() bool {
	if o != nil && !IsNil(o.Implemented) {
		return true
	}

	return false
}

// SetImplemented gets a reference to the given int32 and assigns it to the Implemented field.
func (o *ProjectAnalyticsSuggestionStats) SetImplemented(v int32) {
	o.Implemented = &v
}

// GetAcceptanceRate returns the AcceptanceRate field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetAcceptanceRate() float32 {
	if o == nil || IsNil(o.AcceptanceRate) {
		var ret float32
		return ret
	}
	return *o.AcceptanceRate
}

// GetAcceptanceRateOk returns a tuple with the AcceptanceRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetAcceptanceRateOk() (*float32, bool) {
	if o == nil || IsNil(o.AcceptanceRate) {
		return nil, false
	}
	return o.AcceptanceRate, true
}

// HasAcceptanceRate returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasAcceptanceRate() bool {
	if o != nil && !IsNil(o.AcceptanceRate) {
		return true
	}

	return false
}

// SetAcceptanceRate gets a reference to the given float32 and assigns it to the AcceptanceRate field.
func (o *ProjectAnalyticsSuggestionStats) SetAcceptanceRate(v float32) {
	o.AcceptanceRate = &v
}

// GetImplementationRate returns the ImplementationRate field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetImplementationRate() float32 {
	if o == nil || IsNil(o.ImplementationRate) {
		var ret float32
		return ret
	}
	return *o.ImplementationRate
}

// GetImplementationRateOk returns a tuple with the ImplementationRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetImplementationRateOk() (*float32, bool) {
	if o == nil || IsNil(o.ImplementationRate) {
		return nil, false
	}
	return o.ImplementationRate, true
}

// HasImplementationRate returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasImplementationRate() bool {
	if o != nil && !IsNil(o.ImplementationRate) {
		return true
	}

	return false
}

// SetImplementationRate gets a reference to the given float32 and assigns it to the ImplementationRate field.
func (o *ProjectAnalyticsSuggestionStats) SetImplementationRate(v float32) {
	o.ImplementationRate = &v
}

// GetAvgRelevanceScore returns the AvgRelevanceScore field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetAvgRelevanceScore() float32 {
	if o == nil || IsNil(o.AvgRelevanceScore) {
		var ret float32
		return ret
	}
	return *o.AvgRelevanceScore
}

// GetAvgRelevanceScoreOk returns a tuple with the AvgRelevanceScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetAvgRelevanceScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgRelevanceScore) {
		return nil, false
	}
	return o.AvgRelevanceScore, true
}

// HasAvgRelevanceScore returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasAvgRelevanceScore() bool {
	if o != nil && !IsNil(o.AvgRelevanceScore) {
		return true
	}

	return false
}

// SetAvgRelevanceScore gets a reference to the given float32 and assigns it to the AvgRelevanceScore field.
func (o *ProjectAnalyticsSuggestionStats) SetAvgRelevanceScore(v float32) {
	o.AvgRelevanceScore = &v
}

// GetRelevanceScoreDistribution returns the RelevanceScoreDistribution field value if set, zero value otherwise.
func (o *ProjectAnalyticsSuggestionStats) GetRelevanceScoreDistribution() map[string]interface{} {
	if o == nil || IsNil(o.RelevanceScoreDistribution) {
		var ret map[string]interface{}
		return ret
	}
	return o.RelevanceScoreDistribution
}

// GetRelevanceScoreDistributionOk returns a tuple with the RelevanceScoreDistribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSuggestionStats) GetRelevanceScoreDistributionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RelevanceScoreDistribution) {
		return map[string]interface{}{}, false
	}
	return o.RelevanceScoreDistribution, true
}

// HasRelevanceScoreDistribution returns a boolean if a field has been set.
func (o *ProjectAnalyticsSuggestionStats) HasRelevanceScoreDistribution() bool {
	if o != nil && !IsNil(o.RelevanceScoreDistribution) {
		return true
	}

	return false
}

// SetRelevanceScoreDistribution gets a reference to the given map[string]interface{} and assigns it to the RelevanceScoreDistribution field.
func (o *ProjectAnalyticsSuggestionStats) SetRelevanceScoreDistribution(v map[string]interface{}) {
	o.RelevanceScoreDistribution = v
}

func (o ProjectAnalyticsSuggestionStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAnalyticsSuggestionStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Pending) {
		toSerialize["pending"] = o.Pending
	}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !IsNil(o.Rejected) {
		toSerialize["rejected"] = o.Rejected
	}
	if !IsNil(o.Implemented) {
		toSerialize["implemented"] = o.Implemented
	}
	if !IsNil(o.AcceptanceRate) {
		toSerialize["acceptanceRate"] = o.AcceptanceRate
	}
	if !IsNil(o.ImplementationRate) {
		toSerialize["implementationRate"] = o.ImplementationRate
	}
	if !IsNil(o.AvgRelevanceScore) {
		toSerialize["avgRelevanceScore"] = o.AvgRelevanceScore
	}
	if !IsNil(o.RelevanceScoreDistribution) {
		toSerialize["relevanceScoreDistribution"] = o.RelevanceScoreDistribution
	}
	return toSerialize, nil
}

type NullableProjectAnalyticsSuggestionStats struct {
	value *ProjectAnalyticsSuggestionStats
	isSet bool
}

func (v NullableProjectAnalyticsSuggestionStats) Get() *ProjectAnalyticsSuggestionStats {
	return v.value
}

func (v *NullableProjectAnalyticsSuggestionStats) Set(val *ProjectAnalyticsSuggestionStats) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAnalyticsSuggestionStats) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAnalyticsSuggestionStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAnalyticsSuggestionStats(val *ProjectAnalyticsSuggestionStats) *NullableProjectAnalyticsSuggestionStats {
	return &NullableProjectAnalyticsSuggestionStats{value: val, isSet: true}
}

func (v NullableProjectAnalyticsSuggestionStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAnalyticsSuggestionStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


