/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the ProjectAnalyticsImplementationStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAnalyticsImplementationStats{}

// ProjectAnalyticsImplementationStats struct for ProjectAnalyticsImplementationStats
type ProjectAnalyticsImplementationStats struct {
	Total *int32 `json:"total,omitempty"`
	Success *int32 `json:"success,omitempty"`
	Failed *int32 `json:"failed,omitempty"`
	Pending *int32 `json:"pending,omitempty"`
	InProgress *int32 `json:"inProgress,omitempty"`
	SuccessRate *float32 `json:"successRate,omitempty"`
	AvgCreditsUsed *float32 `json:"avgCreditsUsed,omitempty"`
	PlatformBreakdown map[string]interface{} `json:"platformBreakdown,omitempty"`
}

// NewProjectAnalyticsImplementationStats instantiates a new ProjectAnalyticsImplementationStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAnalyticsImplementationStats() *ProjectAnalyticsImplementationStats {
	this := ProjectAnalyticsImplementationStats{}
	return &this
}

// NewProjectAnalyticsImplementationStatsWithDefaults instantiates a new ProjectAnalyticsImplementationStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAnalyticsImplementationStatsWithDefaults() *ProjectAnalyticsImplementationStats {
	this := ProjectAnalyticsImplementationStats{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ProjectAnalyticsImplementationStats) SetTotal(v int32) {
	o.Total = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetSuccess() int32 {
	if o == nil || IsNil(o.Success) {
		var ret int32
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetSuccessOk() (*int32, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given int32 and assigns it to the Success field.
func (o *ProjectAnalyticsImplementationStats) SetSuccess(v int32) {
	o.Success = &v
}

// GetFailed returns the Failed field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetFailed() int32 {
	if o == nil || IsNil(o.Failed) {
		var ret int32
		return ret
	}
	return *o.Failed
}

// GetFailedOk returns a tuple with the Failed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetFailedOk() (*int32, bool) {
	if o == nil || IsNil(o.Failed) {
		return nil, false
	}
	return o.Failed, true
}

// HasFailed returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasFailed() bool {
	if o != nil && !IsNil(o.Failed) {
		return true
	}

	return false
}

// SetFailed gets a reference to the given int32 and assigns it to the Failed field.
func (o *ProjectAnalyticsImplementationStats) SetFailed(v int32) {
	o.Failed = &v
}

// GetPending returns the Pending field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetPending() int32 {
	if o == nil || IsNil(o.Pending) {
		var ret int32
		return ret
	}
	return *o.Pending
}

// GetPendingOk returns a tuple with the Pending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetPendingOk() (*int32, bool) {
	if o == nil || IsNil(o.Pending) {
		return nil, false
	}
	return o.Pending, true
}

// HasPending returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasPending() bool {
	if o != nil && !IsNil(o.Pending) {
		return true
	}

	return false
}

// SetPending gets a reference to the given int32 and assigns it to the Pending field.
func (o *ProjectAnalyticsImplementationStats) SetPending(v int32) {
	o.Pending = &v
}

// GetInProgress returns the InProgress field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetInProgress() int32 {
	if o == nil || IsNil(o.InProgress) {
		var ret int32
		return ret
	}
	return *o.InProgress
}

// GetInProgressOk returns a tuple with the InProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetInProgressOk() (*int32, bool) {
	if o == nil || IsNil(o.InProgress) {
		return nil, false
	}
	return o.InProgress, true
}

// HasInProgress returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasInProgress() bool {
	if o != nil && !IsNil(o.InProgress) {
		return true
	}

	return false
}

// SetInProgress gets a reference to the given int32 and assigns it to the InProgress field.
func (o *ProjectAnalyticsImplementationStats) SetInProgress(v int32) {
	o.InProgress = &v
}

// GetSuccessRate returns the SuccessRate field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetSuccessRate() float32 {
	if o == nil || IsNil(o.SuccessRate) {
		var ret float32
		return ret
	}
	return *o.SuccessRate
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetSuccessRateOk() (*float32, bool) {
	if o == nil || IsNil(o.SuccessRate) {
		return nil, false
	}
	return o.SuccessRate, true
}

// HasSuccessRate returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasSuccessRate() bool {
	if o != nil && !IsNil(o.SuccessRate) {
		return true
	}

	return false
}

// SetSuccessRate gets a reference to the given float32 and assigns it to the SuccessRate field.
func (o *ProjectAnalyticsImplementationStats) SetSuccessRate(v float32) {
	o.SuccessRate = &v
}

// GetAvgCreditsUsed returns the AvgCreditsUsed field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetAvgCreditsUsed() float32 {
	if o == nil || IsNil(o.AvgCreditsUsed) {
		var ret float32
		return ret
	}
	return *o.AvgCreditsUsed
}

// GetAvgCreditsUsedOk returns a tuple with the AvgCreditsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetAvgCreditsUsedOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgCreditsUsed) {
		return nil, false
	}
	return o.AvgCreditsUsed, true
}

// HasAvgCreditsUsed returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasAvgCreditsUsed() bool {
	if o != nil && !IsNil(o.AvgCreditsUsed) {
		return true
	}

	return false
}

// SetAvgCreditsUsed gets a reference to the given float32 and assigns it to the AvgCreditsUsed field.
func (o *ProjectAnalyticsImplementationStats) SetAvgCreditsUsed(v float32) {
	o.AvgCreditsUsed = &v
}

// GetPlatformBreakdown returns the PlatformBreakdown field value if set, zero value otherwise.
func (o *ProjectAnalyticsImplementationStats) GetPlatformBreakdown() map[string]interface{} {
	if o == nil || IsNil(o.PlatformBreakdown) {
		var ret map[string]interface{}
		return ret
	}
	return o.PlatformBreakdown
}

// GetPlatformBreakdownOk returns a tuple with the PlatformBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsImplementationStats) GetPlatformBreakdownOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PlatformBreakdown) {
		return map[string]interface{}{}, false
	}
	return o.PlatformBreakdown, true
}

// HasPlatformBreakdown returns a boolean if a field has been set.
func (o *ProjectAnalyticsImplementationStats) HasPlatformBreakdown() bool {
	if o != nil && !IsNil(o.PlatformBreakdown) {
		return true
	}

	return false
}

// SetPlatformBreakdown gets a reference to the given map[string]interface{} and assigns it to the PlatformBreakdown field.
func (o *ProjectAnalyticsImplementationStats) SetPlatformBreakdown(v map[string]interface{}) {
	o.PlatformBreakdown = v
}

func (o ProjectAnalyticsImplementationStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAnalyticsImplementationStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Failed) {
		toSerialize["failed"] = o.Failed
	}
	if !IsNil(o.Pending) {
		toSerialize["pending"] = o.Pending
	}
	if !IsNil(o.InProgress) {
		toSerialize["inProgress"] = o.InProgress
	}
	if !IsNil(o.SuccessRate) {
		toSerialize["successRate"] = o.SuccessRate
	}
	if !IsNil(o.AvgCreditsUsed) {
		toSerialize["avgCreditsUsed"] = o.AvgCreditsUsed
	}
	if !IsNil(o.PlatformBreakdown) {
		toSerialize["platformBreakdown"] = o.PlatformBreakdown
	}
	return toSerialize, nil
}

type NullableProjectAnalyticsImplementationStats struct {
	value *ProjectAnalyticsImplementationStats
	isSet bool
}

func (v NullableProjectAnalyticsImplementationStats) Get() *ProjectAnalyticsImplementationStats {
	return v.value
}

func (v *NullableProjectAnalyticsImplementationStats) Set(val *ProjectAnalyticsImplementationStats) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAnalyticsImplementationStats) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAnalyticsImplementationStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAnalyticsImplementationStats(val *ProjectAnalyticsImplementationStats) *NullableProjectAnalyticsImplementationStats {
	return &NullableProjectAnalyticsImplementationStats{value: val, isSet: true}
}

func (v NullableProjectAnalyticsImplementationStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAnalyticsImplementationStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


