/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the PageAllowanceUsageHistoryInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageAllowanceUsageHistoryInner{}

// PageAllowanceUsageHistoryInner struct for PageAllowanceUsageHistoryInner
type PageAllowanceUsageHistoryInner struct {
	Date *string `json:"date,omitempty"`
	PagesIndexed *int32 `json:"pagesIndexed,omitempty"`
}

// NewPageAllowanceUsageHistoryInner instantiates a new PageAllowanceUsageHistoryInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageAllowanceUsageHistoryInner() *PageAllowanceUsageHistoryInner {
	this := PageAllowanceUsageHistoryInner{}
	return &this
}

// NewPageAllowanceUsageHistoryInnerWithDefaults instantiates a new PageAllowanceUsageHistoryInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageAllowanceUsageHistoryInnerWithDefaults() *PageAllowanceUsageHistoryInner {
	this := PageAllowanceUsageHistoryInner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *PageAllowanceUsageHistoryInner) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageAllowanceUsageHistoryInner) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *PageAllowanceUsageHistoryInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *PageAllowanceUsageHistoryInner) SetDate(v string) {
	o.Date = &v
}

// GetPagesIndexed returns the PagesIndexed field value if set, zero value otherwise.
func (o *PageAllowanceUsageHistoryInner) GetPagesIndexed() int32 {
	if o == nil || IsNil(o.PagesIndexed) {
		var ret int32
		return ret
	}
	return *o.PagesIndexed
}

// GetPagesIndexedOk returns a tuple with the PagesIndexed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageAllowanceUsageHistoryInner) GetPagesIndexedOk() (*int32, bool) {
	if o == nil || IsNil(o.PagesIndexed) {
		return nil, false
	}
	return o.PagesIndexed, true
}

// HasPagesIndexed returns a boolean if a field has been set.
func (o *PageAllowanceUsageHistoryInner) HasPagesIndexed() bool {
	if o != nil && !IsNil(o.PagesIndexed) {
		return true
	}

	return false
}

// SetPagesIndexed gets a reference to the given int32 and assigns it to the PagesIndexed field.
func (o *PageAllowanceUsageHistoryInner) SetPagesIndexed(v int32) {
	o.PagesIndexed = &v
}

func (o PageAllowanceUsageHistoryInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageAllowanceUsageHistoryInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.PagesIndexed) {
		toSerialize["pagesIndexed"] = o.PagesIndexed
	}
	return toSerialize, nil
}

type NullablePageAllowanceUsageHistoryInner struct {
	value *PageAllowanceUsageHistoryInner
	isSet bool
}

func (v NullablePageAllowanceUsageHistoryInner) Get() *PageAllowanceUsageHistoryInner {
	return v.value
}

func (v *NullablePageAllowanceUsageHistoryInner) Set(val *PageAllowanceUsageHistoryInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePageAllowanceUsageHistoryInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePageAllowanceUsageHistoryInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageAllowanceUsageHistoryInner(val *PageAllowanceUsageHistoryInner) *NullablePageAllowanceUsageHistoryInner {
	return &NullablePageAllowanceUsageHistoryInner{value: val, isSet: true}
}

func (v NullablePageAllowanceUsageHistoryInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageAllowanceUsageHistoryInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


