/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 

API version: 1.2.0
Contact: support@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RollbackImplementationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RollbackImplementationRequest{}

// RollbackImplementationRequest struct for RollbackImplementationRequest
type RollbackImplementationRequest struct {
	// Reason for rollback
	Reason string `json:"reason"`
	Credentials *CustomCredentials `json:"credentials,omitempty"`
}

type _RollbackImplementationRequest RollbackImplementationRequest

// NewRollbackImplementationRequest instantiates a new RollbackImplementationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRollbackImplementationRequest(reason string) *RollbackImplementationRequest {
	this := RollbackImplementationRequest{}
	this.Reason = reason
	return &this
}

// NewRollbackImplementationRequestWithDefaults instantiates a new RollbackImplementationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRollbackImplementationRequestWithDefaults() *RollbackImplementationRequest {
	this := RollbackImplementationRequest{}
	return &this
}

// GetReason returns the Reason field value
func (o *RollbackImplementationRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *RollbackImplementationRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *RollbackImplementationRequest) SetReason(v string) {
	o.Reason = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *RollbackImplementationRequest) GetCredentials() CustomCredentials {
	if o == nil || IsNil(o.Credentials) {
		var ret CustomCredentials
		return ret
	}
	return *o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RollbackImplementationRequest) GetCredentialsOk() (*CustomCredentials, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *RollbackImplementationRequest) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given CustomCredentials and assigns it to the Credentials field.
func (o *RollbackImplementationRequest) SetCredentials(v CustomCredentials) {
	o.Credentials = &v
}

func (o RollbackImplementationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RollbackImplementationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

func (o *RollbackImplementationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRollbackImplementationRequest := _RollbackImplementationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRollbackImplementationRequest)

	if err != nil {
		return err
	}

	*o = RollbackImplementationRequest(varRollbackImplementationRequest)

	return err
}

type NullableRollbackImplementationRequest struct {
	value *RollbackImplementationRequest
	isSet bool
}

func (v NullableRollbackImplementationRequest) Get() *RollbackImplementationRequest {
	return v.value
}

func (v *NullableRollbackImplementationRequest) Set(val *RollbackImplementationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRollbackImplementationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRollbackImplementationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollbackImplementationRequest(val *RollbackImplementationRequest) *NullableRollbackImplementationRequest {
	return &NullableRollbackImplementationRequest{value: val, isSet: true}
}

func (v NullableRollbackImplementationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollbackImplementationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


