/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the PagePricing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagePricing{}

// PagePricing struct for PagePricing
type PagePricing struct {
	Tiers []PagePricingTiersInner `json:"tiers,omitempty"`
	PagePacks []PagePricingPagePacksInner `json:"pagePacks,omitempty"`
}

// NewPagePricing instantiates a new PagePricing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagePricing() *PagePricing {
	this := PagePricing{}
	return &this
}

// NewPagePricingWithDefaults instantiates a new PagePricing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagePricingWithDefaults() *PagePricing {
	this := PagePricing{}
	return &this
}

// GetTiers returns the Tiers field value if set, zero value otherwise.
func (o *PagePricing) GetTiers() []PagePricingTiersInner {
	if o == nil || IsNil(o.Tiers) {
		var ret []PagePricingTiersInner
		return ret
	}
	return o.Tiers
}

// GetTiersOk returns a tuple with the Tiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagePricing) GetTiersOk() ([]PagePricingTiersInner, bool) {
	if o == nil || IsNil(o.Tiers) {
		return nil, false
	}
	return o.Tiers, true
}

// HasTiers returns a boolean if a field has been set.
func (o *PagePricing) HasTiers() bool {
	if o != nil && !IsNil(o.Tiers) {
		return true
	}

	return false
}

// SetTiers gets a reference to the given []PagePricingTiersInner and assigns it to the Tiers field.
func (o *PagePricing) SetTiers(v []PagePricingTiersInner) {
	o.Tiers = v
}

// GetPagePacks returns the PagePacks field value if set, zero value otherwise.
func (o *PagePricing) GetPagePacks() []PagePricingPagePacksInner {
	if o == nil || IsNil(o.PagePacks) {
		var ret []PagePricingPagePacksInner
		return ret
	}
	return o.PagePacks
}

// GetPagePacksOk returns a tuple with the PagePacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagePricing) GetPagePacksOk() ([]PagePricingPagePacksInner, bool) {
	if o == nil || IsNil(o.PagePacks) {
		return nil, false
	}
	return o.PagePacks, true
}

// HasPagePacks returns a boolean if a field has been set.
func (o *PagePricing) HasPagePacks() bool {
	if o != nil && !IsNil(o.PagePacks) {
		return true
	}

	return false
}

// SetPagePacks gets a reference to the given []PagePricingPagePacksInner and assigns it to the PagePacks field.
func (o *PagePricing) SetPagePacks(v []PagePricingPagePacksInner) {
	o.PagePacks = v
}

func (o PagePricing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagePricing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tiers) {
		toSerialize["tiers"] = o.Tiers
	}
	if !IsNil(o.PagePacks) {
		toSerialize["pagePacks"] = o.PagePacks
	}
	return toSerialize, nil
}

type NullablePagePricing struct {
	value *PagePricing
	isSet bool
}

func (v NullablePagePricing) Get() *PagePricing {
	return v.value
}

func (v *NullablePagePricing) Set(val *PagePricing) {
	v.value = val
	v.isSet = true
}

func (v NullablePagePricing) IsSet() bool {
	return v.isSet
}

func (v *NullablePagePricing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagePricing(val *PagePricing) *NullablePagePricing {
	return &NullablePagePricing{value: val, isSet: true}
}

func (v NullablePagePricing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagePricing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


