/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Page type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Page{}

// Page struct for Page
type Page struct {
	// Page identifier
	Id string `json:"id"`
	// Project identifier
	ProjectId string `json:"projectId"`
	// Page URL
	Url string `json:"url"`
	// Page title
	Title NullableString `json:"title,omitempty"`
	// Word count
	WordCount NullableInt32 `json:"wordCount,omitempty"`
	// Internal links on the page
	InternalLinks []map[string]interface{} `json:"internalLinks,omitempty"`
	// External links on the page
	ExternalLinks []map[string]interface{} `json:"externalLinks,omitempty"`
	// Last sync timestamp
	SyncedAt NullableTime `json:"syncedAt,omitempty"`
	// Last update timestamp
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
}

type _Page Page

// NewPage instantiates a new Page object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPage(id string, projectId string, url string) *Page {
	this := Page{}
	this.Id = id
	this.ProjectId = projectId
	this.Url = url
	return &this
}

// NewPageWithDefaults instantiates a new Page object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageWithDefaults() *Page {
	this := Page{}
	return &this
}

// GetId returns the Id field value
func (o *Page) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Page) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Page) SetId(v string) {
	o.Id = v
}

// GetProjectId returns the ProjectId field value
func (o *Page) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *Page) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *Page) SetProjectId(v string) {
	o.ProjectId = v
}

// GetUrl returns the Url field value
func (o *Page) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Page) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Page) SetUrl(v string) {
	o.Url = v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Page) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Page) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *Page) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *Page) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *Page) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *Page) UnsetTitle() {
	o.Title.Unset()
}

// GetWordCount returns the WordCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Page) GetWordCount() int32 {
	if o == nil || IsNil(o.WordCount.Get()) {
		var ret int32
		return ret
	}
	return *o.WordCount.Get()
}

// GetWordCountOk returns a tuple with the WordCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Page) GetWordCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WordCount.Get(), o.WordCount.IsSet()
}

// HasWordCount returns a boolean if a field has been set.
func (o *Page) HasWordCount() bool {
	if o != nil && o.WordCount.IsSet() {
		return true
	}

	return false
}

// SetWordCount gets a reference to the given NullableInt32 and assigns it to the WordCount field.
func (o *Page) SetWordCount(v int32) {
	o.WordCount.Set(&v)
}
// SetWordCountNil sets the value for WordCount to be an explicit nil
func (o *Page) SetWordCountNil() {
	o.WordCount.Set(nil)
}

// UnsetWordCount ensures that no value is present for WordCount, not even an explicit nil
func (o *Page) UnsetWordCount() {
	o.WordCount.Unset()
}

// GetInternalLinks returns the InternalLinks field value if set, zero value otherwise.
func (o *Page) GetInternalLinks() []map[string]interface{} {
	if o == nil || IsNil(o.InternalLinks) {
		var ret []map[string]interface{}
		return ret
	}
	return o.InternalLinks
}

// GetInternalLinksOk returns a tuple with the InternalLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Page) GetInternalLinksOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.InternalLinks) {
		return nil, false
	}
	return o.InternalLinks, true
}

// HasInternalLinks returns a boolean if a field has been set.
func (o *Page) HasInternalLinks() bool {
	if o != nil && !IsNil(o.InternalLinks) {
		return true
	}

	return false
}

// SetInternalLinks gets a reference to the given []map[string]interface{} and assigns it to the InternalLinks field.
func (o *Page) SetInternalLinks(v []map[string]interface{}) {
	o.InternalLinks = v
}

// GetExternalLinks returns the ExternalLinks field value if set, zero value otherwise.
func (o *Page) GetExternalLinks() []map[string]interface{} {
	if o == nil || IsNil(o.ExternalLinks) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ExternalLinks
}

// GetExternalLinksOk returns a tuple with the ExternalLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Page) GetExternalLinksOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExternalLinks) {
		return nil, false
	}
	return o.ExternalLinks, true
}

// HasExternalLinks returns a boolean if a field has been set.
func (o *Page) HasExternalLinks() bool {
	if o != nil && !IsNil(o.ExternalLinks) {
		return true
	}

	return false
}

// SetExternalLinks gets a reference to the given []map[string]interface{} and assigns it to the ExternalLinks field.
func (o *Page) SetExternalLinks(v []map[string]interface{}) {
	o.ExternalLinks = v
}

// GetSyncedAt returns the SyncedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Page) GetSyncedAt() time.Time {
	if o == nil || IsNil(o.SyncedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SyncedAt.Get()
}

// GetSyncedAtOk returns a tuple with the SyncedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Page) GetSyncedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SyncedAt.Get(), o.SyncedAt.IsSet()
}

// HasSyncedAt returns a boolean if a field has been set.
func (o *Page) HasSyncedAt() bool {
	if o != nil && o.SyncedAt.IsSet() {
		return true
	}

	return false
}

// SetSyncedAt gets a reference to the given NullableTime and assigns it to the SyncedAt field.
func (o *Page) SetSyncedAt(v time.Time) {
	o.SyncedAt.Set(&v)
}
// SetSyncedAtNil sets the value for SyncedAt to be an explicit nil
func (o *Page) SetSyncedAtNil() {
	o.SyncedAt.Set(nil)
}

// UnsetSyncedAt ensures that no value is present for SyncedAt, not even an explicit nil
func (o *Page) UnsetSyncedAt() {
	o.SyncedAt.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Page) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Page) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Page) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *Page) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *Page) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *Page) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o Page) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Page) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["projectId"] = o.ProjectId
	toSerialize["url"] = o.Url
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.WordCount.IsSet() {
		toSerialize["wordCount"] = o.WordCount.Get()
	}
	if !IsNil(o.InternalLinks) {
		toSerialize["internalLinks"] = o.InternalLinks
	}
	if !IsNil(o.ExternalLinks) {
		toSerialize["externalLinks"] = o.ExternalLinks
	}
	if o.SyncedAt.IsSet() {
		toSerialize["syncedAt"] = o.SyncedAt.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

func (o *Page) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"projectId",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPage := _Page{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPage)

	if err != nil {
		return err
	}

	*o = Page(varPage)

	return err
}

type NullablePage struct {
	value *Page
	isSet bool
}

func (v NullablePage) Get() *Page {
	return v.value
}

func (v *NullablePage) Set(val *Page) {
	v.value = val
	v.isSet = true
}

func (v NullablePage) IsSet() bool {
	return v.isSet
}

func (v *NullablePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePage(val *Page) *NullablePage {
	return &NullablePage{value: val, isSet: true}
}

func (v NullablePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


