/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PageLimitStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageLimitStatus{}

// PageLimitStatus struct for PageLimitStatus
type PageLimitStatus struct {
	// Page limit
	Limit int32 `json:"limit"`
	// Pages used
	Used int32 `json:"used"`
	// Pages remaining
	Remaining int32 `json:"remaining"`
}

type _PageLimitStatus PageLimitStatus

// NewPageLimitStatus instantiates a new PageLimitStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageLimitStatus(limit int32, used int32, remaining int32) *PageLimitStatus {
	this := PageLimitStatus{}
	this.Limit = limit
	this.Used = used
	this.Remaining = remaining
	return &this
}

// NewPageLimitStatusWithDefaults instantiates a new PageLimitStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageLimitStatusWithDefaults() *PageLimitStatus {
	this := PageLimitStatus{}
	return &this
}

// GetLimit returns the Limit field value
func (o *PageLimitStatus) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *PageLimitStatus) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *PageLimitStatus) SetLimit(v int32) {
	o.Limit = v
}

// GetUsed returns the Used field value
func (o *PageLimitStatus) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *PageLimitStatus) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *PageLimitStatus) SetUsed(v int32) {
	o.Used = v
}

// GetRemaining returns the Remaining field value
func (o *PageLimitStatus) GetRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value
// and a boolean to check if the value has been set.
func (o *PageLimitStatus) GetRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remaining, true
}

// SetRemaining sets field value
func (o *PageLimitStatus) SetRemaining(v int32) {
	o.Remaining = v
}

func (o PageLimitStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageLimitStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["limit"] = o.Limit
	toSerialize["used"] = o.Used
	toSerialize["remaining"] = o.Remaining
	return toSerialize, nil
}

func (o *PageLimitStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"limit",
		"used",
		"remaining",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPageLimitStatus := _PageLimitStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPageLimitStatus)

	if err != nil {
		return err
	}

	*o = PageLimitStatus(varPageLimitStatus)

	return err
}

type NullablePageLimitStatus struct {
	value *PageLimitStatus
	isSet bool
}

func (v NullablePageLimitStatus) Get() *PageLimitStatus {
	return v.value
}

func (v *NullablePageLimitStatus) Set(val *PageLimitStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePageLimitStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePageLimitStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageLimitStatus(val *PageLimitStatus) *NullablePageLimitStatus {
	return &NullablePageLimitStatus{value: val, isSet: true}
}

func (v NullablePageLimitStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageLimitStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


