/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"time"
)

// checks if the ProjectAnalyticsSyncStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAnalyticsSyncStats{}

// ProjectAnalyticsSyncStats struct for ProjectAnalyticsSyncStats
type ProjectAnalyticsSyncStats struct {
	LastSyncDate NullableTime `json:"lastSyncDate,omitempty"`
	TotalPagesSynced *int32 `json:"totalPagesSynced,omitempty"`
}

// NewProjectAnalyticsSyncStats instantiates a new ProjectAnalyticsSyncStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAnalyticsSyncStats() *ProjectAnalyticsSyncStats {
	this := ProjectAnalyticsSyncStats{}
	return &this
}

// NewProjectAnalyticsSyncStatsWithDefaults instantiates a new ProjectAnalyticsSyncStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAnalyticsSyncStatsWithDefaults() *ProjectAnalyticsSyncStats {
	this := ProjectAnalyticsSyncStats{}
	return &this
}

// GetLastSyncDate returns the LastSyncDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectAnalyticsSyncStats) GetLastSyncDate() time.Time {
	if o == nil || IsNil(o.LastSyncDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncDate.Get()
}

// GetLastSyncDateOk returns a tuple with the LastSyncDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectAnalyticsSyncStats) GetLastSyncDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastSyncDate.Get(), o.LastSyncDate.IsSet()
}

// HasLastSyncDate returns a boolean if a field has been set.
func (o *ProjectAnalyticsSyncStats) HasLastSyncDate() bool {
	if o != nil && o.LastSyncDate.IsSet() {
		return true
	}

	return false
}

// SetLastSyncDate gets a reference to the given NullableTime and assigns it to the LastSyncDate field.
func (o *ProjectAnalyticsSyncStats) SetLastSyncDate(v time.Time) {
	o.LastSyncDate.Set(&v)
}
// SetLastSyncDateNil sets the value for LastSyncDate to be an explicit nil
func (o *ProjectAnalyticsSyncStats) SetLastSyncDateNil() {
	o.LastSyncDate.Set(nil)
}

// UnsetLastSyncDate ensures that no value is present for LastSyncDate, not even an explicit nil
func (o *ProjectAnalyticsSyncStats) UnsetLastSyncDate() {
	o.LastSyncDate.Unset()
}

// GetTotalPagesSynced returns the TotalPagesSynced field value if set, zero value otherwise.
func (o *ProjectAnalyticsSyncStats) GetTotalPagesSynced() int32 {
	if o == nil || IsNil(o.TotalPagesSynced) {
		var ret int32
		return ret
	}
	return *o.TotalPagesSynced
}

// GetTotalPagesSyncedOk returns a tuple with the TotalPagesSynced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsSyncStats) GetTotalPagesSyncedOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPagesSynced) {
		return nil, false
	}
	return o.TotalPagesSynced, true
}

// HasTotalPagesSynced returns a boolean if a field has been set.
func (o *ProjectAnalyticsSyncStats) HasTotalPagesSynced() bool {
	if o != nil && !IsNil(o.TotalPagesSynced) {
		return true
	}

	return false
}

// SetTotalPagesSynced gets a reference to the given int32 and assigns it to the TotalPagesSynced field.
func (o *ProjectAnalyticsSyncStats) SetTotalPagesSynced(v int32) {
	o.TotalPagesSynced = &v
}

func (o ProjectAnalyticsSyncStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAnalyticsSyncStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.LastSyncDate.IsSet() {
		toSerialize["lastSyncDate"] = o.LastSyncDate.Get()
	}
	if !IsNil(o.TotalPagesSynced) {
		toSerialize["totalPagesSynced"] = o.TotalPagesSynced
	}
	return toSerialize, nil
}

type NullableProjectAnalyticsSyncStats struct {
	value *ProjectAnalyticsSyncStats
	isSet bool
}

func (v NullableProjectAnalyticsSyncStats) Get() *ProjectAnalyticsSyncStats {
	return v.value
}

func (v *NullableProjectAnalyticsSyncStats) Set(val *ProjectAnalyticsSyncStats) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAnalyticsSyncStats) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAnalyticsSyncStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAnalyticsSyncStats(val *ProjectAnalyticsSyncStats) *NullableProjectAnalyticsSyncStats {
	return &NullableProjectAnalyticsSyncStats{value: val, isSet: true}
}

func (v NullableProjectAnalyticsSyncStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAnalyticsSyncStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


