/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyContentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyContentRequest{}

// VerifyContentRequest struct for VerifyContentRequest
type VerifyContentRequest struct {
	// URL of the page to verify
	PageUrl string `json:"pageUrl"`
	// ID of the suggestion to verify
	SuggestionId string `json:"suggestionId"`
}

type _VerifyContentRequest VerifyContentRequest

// NewVerifyContentRequest instantiates a new VerifyContentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyContentRequest(pageUrl string, suggestionId string) *VerifyContentRequest {
	this := VerifyContentRequest{}
	this.PageUrl = pageUrl
	this.SuggestionId = suggestionId
	return &this
}

// NewVerifyContentRequestWithDefaults instantiates a new VerifyContentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyContentRequestWithDefaults() *VerifyContentRequest {
	this := VerifyContentRequest{}
	return &this
}

// GetPageUrl returns the PageUrl field value
func (o *VerifyContentRequest) GetPageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PageUrl
}

// GetPageUrlOk returns a tuple with the PageUrl field value
// and a boolean to check if the value has been set.
func (o *VerifyContentRequest) GetPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageUrl, true
}

// SetPageUrl sets field value
func (o *VerifyContentRequest) SetPageUrl(v string) {
	o.PageUrl = v
}

// GetSuggestionId returns the SuggestionId field value
func (o *VerifyContentRequest) GetSuggestionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuggestionId
}

// GetSuggestionIdOk returns a tuple with the SuggestionId field value
// and a boolean to check if the value has been set.
func (o *VerifyContentRequest) GetSuggestionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuggestionId, true
}

// SetSuggestionId sets field value
func (o *VerifyContentRequest) SetSuggestionId(v string) {
	o.SuggestionId = v
}

func (o VerifyContentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyContentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pageUrl"] = o.PageUrl
	toSerialize["suggestionId"] = o.SuggestionId
	return toSerialize, nil
}

func (o *VerifyContentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pageUrl",
		"suggestionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyContentRequest := _VerifyContentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyContentRequest)

	if err != nil {
		return err
	}

	*o = VerifyContentRequest(varVerifyContentRequest)

	return err
}

type NullableVerifyContentRequest struct {
	value *VerifyContentRequest
	isSet bool
}

func (v NullableVerifyContentRequest) Get() *VerifyContentRequest {
	return v.value
}

func (v *NullableVerifyContentRequest) Set(val *VerifyContentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyContentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyContentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyContentRequest(val *VerifyContentRequest) *NullableVerifyContentRequest {
	return &NullableVerifyContentRequest{value: val, isSet: true}
}

func (v NullableVerifyContentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyContentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


