/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the ProjectAnalyticsContentStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAnalyticsContentStats{}

// ProjectAnalyticsContentStats struct for ProjectAnalyticsContentStats
type ProjectAnalyticsContentStats struct {
	TotalPages *int32 `json:"totalPages,omitempty"`
	AvgWordCount *float32 `json:"avgWordCount,omitempty"`
	TotalWords *int32 `json:"totalWords,omitempty"`
	PagesWithLinks *int32 `json:"pagesWithLinks,omitempty"`
	WordCountDistribution map[string]interface{} `json:"wordCountDistribution,omitempty"`
	InternalLinkDistribution map[string]interface{} `json:"internalLinkDistribution,omitempty"`
}

// NewProjectAnalyticsContentStats instantiates a new ProjectAnalyticsContentStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAnalyticsContentStats() *ProjectAnalyticsContentStats {
	this := ProjectAnalyticsContentStats{}
	return &this
}

// NewProjectAnalyticsContentStatsWithDefaults instantiates a new ProjectAnalyticsContentStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAnalyticsContentStatsWithDefaults() *ProjectAnalyticsContentStats {
	this := ProjectAnalyticsContentStats{}
	return &this
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *ProjectAnalyticsContentStats) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsContentStats) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *ProjectAnalyticsContentStats) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *ProjectAnalyticsContentStats) SetTotalPages(v int32) {
	o.TotalPages = &v
}

// GetAvgWordCount returns the AvgWordCount field value if set, zero value otherwise.
func (o *ProjectAnalyticsContentStats) GetAvgWordCount() float32 {
	if o == nil || IsNil(o.AvgWordCount) {
		var ret float32
		return ret
	}
	return *o.AvgWordCount
}

// GetAvgWordCountOk returns a tuple with the AvgWordCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsContentStats) GetAvgWordCountOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgWordCount) {
		return nil, false
	}
	return o.AvgWordCount, true
}

// HasAvgWordCount returns a boolean if a field has been set.
func (o *ProjectAnalyticsContentStats) HasAvgWordCount() bool {
	if o != nil && !IsNil(o.AvgWordCount) {
		return true
	}

	return false
}

// SetAvgWordCount gets a reference to the given float32 and assigns it to the AvgWordCount field.
func (o *ProjectAnalyticsContentStats) SetAvgWordCount(v float32) {
	o.AvgWordCount = &v
}

// GetTotalWords returns the TotalWords field value if set, zero value otherwise.
func (o *ProjectAnalyticsContentStats) GetTotalWords() int32 {
	if o == nil || IsNil(o.TotalWords) {
		var ret int32
		return ret
	}
	return *o.TotalWords
}

// GetTotalWordsOk returns a tuple with the TotalWords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsContentStats) GetTotalWordsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalWords) {
		return nil, false
	}
	return o.TotalWords, true
}

// HasTotalWords returns a boolean if a field has been set.
func (o *ProjectAnalyticsContentStats) HasTotalWords() bool {
	if o != nil && !IsNil(o.TotalWords) {
		return true
	}

	return false
}

// SetTotalWords gets a reference to the given int32 and assigns it to the TotalWords field.
func (o *ProjectAnalyticsContentStats) SetTotalWords(v int32) {
	o.TotalWords = &v
}

// GetPagesWithLinks returns the PagesWithLinks field value if set, zero value otherwise.
func (o *ProjectAnalyticsContentStats) GetPagesWithLinks() int32 {
	if o == nil || IsNil(o.PagesWithLinks) {
		var ret int32
		return ret
	}
	return *o.PagesWithLinks
}

// GetPagesWithLinksOk returns a tuple with the PagesWithLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsContentStats) GetPagesWithLinksOk() (*int32, bool) {
	if o == nil || IsNil(o.PagesWithLinks) {
		return nil, false
	}
	return o.PagesWithLinks, true
}

// HasPagesWithLinks returns a boolean if a field has been set.
func (o *ProjectAnalyticsContentStats) HasPagesWithLinks() bool {
	if o != nil && !IsNil(o.PagesWithLinks) {
		return true
	}

	return false
}

// SetPagesWithLinks gets a reference to the given int32 and assigns it to the PagesWithLinks field.
func (o *ProjectAnalyticsContentStats) SetPagesWithLinks(v int32) {
	o.PagesWithLinks = &v
}

// GetWordCountDistribution returns the WordCountDistribution field value if set, zero value otherwise.
func (o *ProjectAnalyticsContentStats) GetWordCountDistribution() map[string]interface{} {
	if o == nil || IsNil(o.WordCountDistribution) {
		var ret map[string]interface{}
		return ret
	}
	return o.WordCountDistribution
}

// GetWordCountDistributionOk returns a tuple with the WordCountDistribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsContentStats) GetWordCountDistributionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.WordCountDistribution) {
		return map[string]interface{}{}, false
	}
	return o.WordCountDistribution, true
}

// HasWordCountDistribution returns a boolean if a field has been set.
func (o *ProjectAnalyticsContentStats) HasWordCountDistribution() bool {
	if o != nil && !IsNil(o.WordCountDistribution) {
		return true
	}

	return false
}

// SetWordCountDistribution gets a reference to the given map[string]interface{} and assigns it to the WordCountDistribution field.
func (o *ProjectAnalyticsContentStats) SetWordCountDistribution(v map[string]interface{}) {
	o.WordCountDistribution = v
}

// GetInternalLinkDistribution returns the InternalLinkDistribution field value if set, zero value otherwise.
func (o *ProjectAnalyticsContentStats) GetInternalLinkDistribution() map[string]interface{} {
	if o == nil || IsNil(o.InternalLinkDistribution) {
		var ret map[string]interface{}
		return ret
	}
	return o.InternalLinkDistribution
}

// GetInternalLinkDistributionOk returns a tuple with the InternalLinkDistribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAnalyticsContentStats) GetInternalLinkDistributionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.InternalLinkDistribution) {
		return map[string]interface{}{}, false
	}
	return o.InternalLinkDistribution, true
}

// HasInternalLinkDistribution returns a boolean if a field has been set.
func (o *ProjectAnalyticsContentStats) HasInternalLinkDistribution() bool {
	if o != nil && !IsNil(o.InternalLinkDistribution) {
		return true
	}

	return false
}

// SetInternalLinkDistribution gets a reference to the given map[string]interface{} and assigns it to the InternalLinkDistribution field.
func (o *ProjectAnalyticsContentStats) SetInternalLinkDistribution(v map[string]interface{}) {
	o.InternalLinkDistribution = v
}

func (o ProjectAnalyticsContentStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAnalyticsContentStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalPages) {
		toSerialize["totalPages"] = o.TotalPages
	}
	if !IsNil(o.AvgWordCount) {
		toSerialize["avgWordCount"] = o.AvgWordCount
	}
	if !IsNil(o.TotalWords) {
		toSerialize["totalWords"] = o.TotalWords
	}
	if !IsNil(o.PagesWithLinks) {
		toSerialize["pagesWithLinks"] = o.PagesWithLinks
	}
	if !IsNil(o.WordCountDistribution) {
		toSerialize["wordCountDistribution"] = o.WordCountDistribution
	}
	if !IsNil(o.InternalLinkDistribution) {
		toSerialize["internalLinkDistribution"] = o.InternalLinkDistribution
	}
	return toSerialize, nil
}

type NullableProjectAnalyticsContentStats struct {
	value *ProjectAnalyticsContentStats
	isSet bool
}

func (v NullableProjectAnalyticsContentStats) Get() *ProjectAnalyticsContentStats {
	return v.value
}

func (v *NullableProjectAnalyticsContentStats) Set(val *ProjectAnalyticsContentStats) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAnalyticsContentStats) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAnalyticsContentStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAnalyticsContentStats(val *ProjectAnalyticsContentStats) *NullableProjectAnalyticsContentStats {
	return &NullableProjectAnalyticsContentStats{value: val, isSet: true}
}

func (v NullableProjectAnalyticsContentStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAnalyticsContentStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


