/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 

API version: 1.2.0
Contact: support@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the GenerateSuggestions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateSuggestions200Response{}

// GenerateSuggestions200Response struct for GenerateSuggestions200Response
type GenerateSuggestions200Response struct {
	Success *bool `json:"success,omitempty"`
	// Number of suggestions generated
	Count *int32 `json:"count,omitempty"`
	// Top 10 opportunities preview
	Opportunities []LinkOpportunity `json:"opportunities,omitempty"`
}

// NewGenerateSuggestions200Response instantiates a new GenerateSuggestions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateSuggestions200Response() *GenerateSuggestions200Response {
	this := GenerateSuggestions200Response{}
	return &this
}

// NewGenerateSuggestions200ResponseWithDefaults instantiates a new GenerateSuggestions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateSuggestions200ResponseWithDefaults() *GenerateSuggestions200Response {
	this := GenerateSuggestions200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GenerateSuggestions200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateSuggestions200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GenerateSuggestions200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GenerateSuggestions200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GenerateSuggestions200Response) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateSuggestions200Response) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GenerateSuggestions200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GenerateSuggestions200Response) SetCount(v int32) {
	o.Count = &v
}

// GetOpportunities returns the Opportunities field value if set, zero value otherwise.
func (o *GenerateSuggestions200Response) GetOpportunities() []LinkOpportunity {
	if o == nil || IsNil(o.Opportunities) {
		var ret []LinkOpportunity
		return ret
	}
	return o.Opportunities
}

// GetOpportunitiesOk returns a tuple with the Opportunities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateSuggestions200Response) GetOpportunitiesOk() ([]LinkOpportunity, bool) {
	if o == nil || IsNil(o.Opportunities) {
		return nil, false
	}
	return o.Opportunities, true
}

// HasOpportunities returns a boolean if a field has been set.
func (o *GenerateSuggestions200Response) HasOpportunities() bool {
	if o != nil && !IsNil(o.Opportunities) {
		return true
	}

	return false
}

// SetOpportunities gets a reference to the given []LinkOpportunity and assigns it to the Opportunities field.
func (o *GenerateSuggestions200Response) SetOpportunities(v []LinkOpportunity) {
	o.Opportunities = v
}

func (o GenerateSuggestions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateSuggestions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Opportunities) {
		toSerialize["opportunities"] = o.Opportunities
	}
	return toSerialize, nil
}

type NullableGenerateSuggestions200Response struct {
	value *GenerateSuggestions200Response
	isSet bool
}

func (v NullableGenerateSuggestions200Response) Get() *GenerateSuggestions200Response {
	return v.value
}

func (v *NullableGenerateSuggestions200Response) Set(val *GenerateSuggestions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateSuggestions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateSuggestions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateSuggestions200Response(val *GenerateSuggestions200Response) *NullableGenerateSuggestions200Response {
	return &NullableGenerateSuggestions200Response{value: val, isSet: true}
}

func (v NullableGenerateSuggestions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateSuggestions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


