/*
RankVectors API

Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

API version: 1.3.1
Contact: tj@rankvectors.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rankvectors

import (
	"encoding/json"
)

// checks if the GetPageChanges200ResponseSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPageChanges200ResponseSummary{}

// GetPageChanges200ResponseSummary struct for GetPageChanges200ResponseSummary
type GetPageChanges200ResponseSummary struct {
	Total *int32 `json:"total,omitempty"`
	ByStatus map[string]interface{} `json:"byStatus,omitempty"`
}

// NewGetPageChanges200ResponseSummary instantiates a new GetPageChanges200ResponseSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPageChanges200ResponseSummary() *GetPageChanges200ResponseSummary {
	this := GetPageChanges200ResponseSummary{}
	return &this
}

// NewGetPageChanges200ResponseSummaryWithDefaults instantiates a new GetPageChanges200ResponseSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPageChanges200ResponseSummaryWithDefaults() *GetPageChanges200ResponseSummary {
	this := GetPageChanges200ResponseSummary{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetPageChanges200ResponseSummary) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPageChanges200ResponseSummary) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetPageChanges200ResponseSummary) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetPageChanges200ResponseSummary) SetTotal(v int32) {
	o.Total = &v
}

// GetByStatus returns the ByStatus field value if set, zero value otherwise.
func (o *GetPageChanges200ResponseSummary) GetByStatus() map[string]interface{} {
	if o == nil || IsNil(o.ByStatus) {
		var ret map[string]interface{}
		return ret
	}
	return o.ByStatus
}

// GetByStatusOk returns a tuple with the ByStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPageChanges200ResponseSummary) GetByStatusOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ByStatus) {
		return map[string]interface{}{}, false
	}
	return o.ByStatus, true
}

// HasByStatus returns a boolean if a field has been set.
func (o *GetPageChanges200ResponseSummary) HasByStatus() bool {
	if o != nil && !IsNil(o.ByStatus) {
		return true
	}

	return false
}

// SetByStatus gets a reference to the given map[string]interface{} and assigns it to the ByStatus field.
func (o *GetPageChanges200ResponseSummary) SetByStatus(v map[string]interface{}) {
	o.ByStatus = v
}

func (o GetPageChanges200ResponseSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPageChanges200ResponseSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.ByStatus) {
		toSerialize["byStatus"] = o.ByStatus
	}
	return toSerialize, nil
}

type NullableGetPageChanges200ResponseSummary struct {
	value *GetPageChanges200ResponseSummary
	isSet bool
}

func (v NullableGetPageChanges200ResponseSummary) Get() *GetPageChanges200ResponseSummary {
	return v.value
}

func (v *NullableGetPageChanges200ResponseSummary) Set(val *GetPageChanges200ResponseSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPageChanges200ResponseSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPageChanges200ResponseSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPageChanges200ResponseSummary(val *GetPageChanges200ResponseSummary) *NullableGetPageChanges200ResponseSummary {
	return &NullableGetPageChanges200ResponseSummary{value: val, isSet: true}
}

func (v NullableGetPageChanges200ResponseSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPageChanges200ResponseSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


